if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(invocation "${PHOTOC}" exif)
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(check_io_error FALSE)

if(CASE STREQUAL "with_exif" OR CASE STREQUAL "with_gps" OR
   CASE STREQUAL "no_exif")
    if(CASE STREQUAL "with_exif")
        set(FILE_PATH "${FIXTURE_DIR}/with_exif.jpg")
    elseif(CASE STREQUAL "with_gps")
        set(FILE_PATH "${FIXTURE_DIR}/with_gps.jpeg")
    else()
        set(FILE_PATH "${FIXTURE_DIR}/no_exif.jpg")
    endif()
    list(APPEND invocation "${FILE_PATH}")
    file(SIZE "${FILE_PATH}" FILE_SIZE)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/exif-${CASE}.txt" snapshot)
    string(CONFIGURE "${snapshot}" expected_stdout @ONLY)
elseif(CASE STREQUAL "invalid")
    set(path "${FIXTURE_DIR}/invalid.jpg")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(expected_stderr "photoc exif: '${path}': invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "unsupported")
    set(path "${FIXTURE_DIR}/unsupported.png")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(expected_stderr "photoc exif: '${path}': unsupported file type (expected .jpg or .jpeg)\n")
elseif(CASE STREQUAL "missing")
    set(path "${FIXTURE_DIR}/missing.jpg")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(check_io_error TRUE)
elseif(CASE STREQUAL "no_argument")
    set(expected_exit 2)
    set(expected_stderr "photoc exif: expected exactly one file\nUsage: photoc exif <file>\n")
elseif(CASE STREQUAL "extra_argument")
    list(APPEND invocation "${FIXTURE_DIR}/with_exif.jpg" "${FIXTURE_DIR}/no_exif.jpg")
    set(expected_exit 2)
    set(expected_stderr "photoc exif: expected exactly one file\nUsage: photoc exif <file>\n")
elseif(CASE STREQUAL "unknown_option")
    list(APPEND invocation --bogus "${FIXTURE_DIR}/with_exif.jpg")
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '--bogus'\nTry 'photoc --help' for available options.\n")
else()
    message(FATAL_ERROR "Unknown EXIF test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(NOT stdout STREQUAL "${expected_stdout}")
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${stdout}")
endif()
if(check_io_error)
    set(prefix "photoc exif: '${path}': unable to read JPEG file: ")
    string(FIND "${stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected I/O error: ${stderr}")
    endif()
elseif(NOT stderr STREQUAL "${expected_stderr}")
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${stderr}")
endif()
