if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/compress-cli-${CASE}")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")
set(source "${root}/photo.jpeg")
set(output "${root}/photo.compressed.jpeg")
file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${source}")
file(SHA256 "${source}" original_hash)
file(SIZE "${source}" original_size)

set(arguments compress "${source}")
set(expected_exit 0)
set(expected_error "")
set(expected_quality 80)
set(expect_output TRUE)
set(expect_gps TRUE)

if(CASE STREQUAL "default")
elseif(CASE STREQUAL "quality")
    list(APPEND arguments --quality 35)
    set(expected_quality 35)
elseif(CASE STREQUAL "quality_one")
    list(APPEND arguments --quality 1)
    set(expected_quality 1)
elseif(CASE STREQUAL "quality_hundred")
    list(APPEND arguments --quality 100)
    set(expected_quality 100)
elseif(CASE STREQUAL "quality_effect")
    list(APPEND arguments --quality 20)
    set(expected_quality 20)
elseif(CASE STREQUAL "no_exif")
    set(source "${root}/plain.jpg")
    set(output "${root}/plain.compressed.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${source}")
    file(SHA256 "${source}" original_hash)
    file(SIZE "${source}" original_size)
    set(arguments compress "${source}")
    set(expect_gps FALSE)
elseif(CASE STREQUAL "extension")
    set(source "${root}/upper.JPG")
    set(output "${root}/upper.compressed.JPG")
    file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${source}")
    file(SHA256 "${source}" original_hash)
    file(SIZE "${source}" original_size)
    set(arguments compress "${source}")
elseif(CASE STREQUAL "output_dir")
    set(output "${root}/converted/photo.compressed.jpeg")
    list(APPEND arguments --output-dir "${root}/converted")
elseif(CASE STREQUAL "recursive_file")
    list(APPEND arguments --recursive)
    set(expected_exit 2)
    set(expected_error "--recursive requires a directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "output_dir_missing")
    list(APPEND arguments --output-dir)
    set(expected_exit 2)
    set(expected_error "option '--output-dir' requires a value")
    set(expect_output FALSE)
elseif(CASE STREQUAL "output_dir_duplicate")
    list(APPEND arguments --output-dir "${root}/one" --output-dir "${root}/two")
    set(expected_exit 2)
    set(expected_error "option '--output-dir' may be specified only once")
    set(expect_output FALSE)
elseif(CASE STREQUAL "output_dir_conflict")
    file(WRITE "${root}/destination" "sentinel")
    list(APPEND arguments --output-dir "${root}/destination")
    set(expected_exit 1)
    set(expected_error "cannot create output directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "collision")
    file(WRITE "${output}" "sentinel")
    set(expected_exit 1)
    set(expected_error "File exists")
    set(expect_output FALSE)
elseif(CASE STREQUAL "invalid")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${source}")
    file(SHA256 "${source}" original_hash)
    set(expected_exit 1)
    set(expected_error "invalid JPEG")
    set(expect_output FALSE)
elseif(CASE STREQUAL "unsupported")
    set(source "${root}/photo.png")
    set(arguments compress "${source}")
    file(COPY_FILE "${FIXTURE_DIR}/unsupported.png" "${source}")
    set(expected_exit 1)
    set(expected_error "expected a regular JPEG file or directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "missing")
    set(arguments compress "${root}/absent.jpg")
    set(expected_exit 1)
    set(expected_error "No such file or directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "directory")
    file(MAKE_DIRECTORY "${root}/empty")
    set(arguments compress "${root}/empty")
    set(expected_exit 0)
    set(expect_output FALSE)
elseif(CASE STREQUAL "no_argument")
    set(arguments compress)
    set(expected_exit 2)
    set(expected_error "expected exactly one JPEG file or directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "extra_argument")
    set(arguments compress "${source}" extra.jpg)
    set(expected_exit 2)
    set(expected_error "expected exactly one JPEG file or directory")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_missing")
    list(APPEND arguments --quality)
    set(expected_exit 2)
    set(expected_error "option '--quality' requires a value")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_zero")
    list(APPEND arguments --quality 0)
    set(expected_exit 2)
    set(expected_error "invalid quality '0'; use 1-100")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_high")
    list(APPEND arguments --quality 101)
    set(expected_exit 2)
    set(expected_error "invalid quality '101'; use 1-100")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_negative")
    list(APPEND arguments --quality -1)
    set(expected_exit 2)
    set(expected_error "invalid quality '-1'; use 1-100")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_decimal")
    list(APPEND arguments --quality 80.5)
    set(expected_exit 2)
    set(expected_error "invalid quality '80.5'; use 1-100")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_text")
    list(APPEND arguments --quality fast)
    set(expected_exit 2)
    set(expected_error "invalid quality 'fast'; use 1-100")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_duplicate")
    list(APPEND arguments --quality 50 --quality 70)
    set(expected_exit 2)
    set(expected_error "option '--quality' may be specified only once")
    set(expect_output FALSE)
elseif(CASE STREQUAL "json")
    list(APPEND arguments --json)
    set(expected_exit 2)
    set(expected_error "--json is not supported")
    set(expect_output FALSE)
else()
    message(FATAL_ERROR "Unknown compress case: ${CASE}")
endif()

execute_process(COMMAND "${PHOTOC}" ${arguments}
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT "${exit_code}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Exit ${exit_code}, expected ${expected_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(expected_error AND NOT stderr MATCHES "${expected_error}")
    message(FATAL_ERROR "Missing diagnostic\nstderr: ${stderr}")
endif()
if(expected_exit EQUAL 0 AND NOT stderr STREQUAL "")
    message(FATAL_ERROR "Unexpected stderr: ${stderr}")
endif()

if(expect_output)
    if(NOT EXISTS "${output}")
        message(FATAL_ERROR "Expected compressed output: ${output}")
    endif()
    file(SIZE "${output}" compressed_size)
    math(EXPR saved "${original_size} - ${compressed_size}")
    if(NOT stdout MATCHES "Output: ${output}" OR
       NOT stdout MATCHES "Quality: ${expected_quality}" OR
       NOT stdout MATCHES "Original size: ${original_size} bytes" OR
       NOT stdout MATCHES "Compressed size: ${compressed_size} bytes" OR
       NOT stdout MATCHES "Bytes saved: ${saved} bytes" OR
       NOT stdout MATCHES "Percentage saved: -?[0-9]+\\.[0-9][0-9]%")
        message(FATAL_ERROR "Incorrect compression report: ${stdout}")
    endif()
    file(SHA256 "${source}" after_hash)
    if(NOT after_hash STREQUAL original_hash)
        message(FATAL_ERROR "Source JPEG changed")
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${output}" --json
        RESULT_VARIABLE metadata_exit OUTPUT_VARIABLE metadata ERROR_VARIABLE metadata_error)
    if(NOT metadata_exit EQUAL 0 OR NOT metadata_error STREQUAL "")
        message(FATAL_ERROR "Compressed JPEG invalid: ${metadata_error}")
    endif()
    string(JSON width GET "${metadata}" image width)
    string(JSON height GET "${metadata}" image height)
    string(JSON gps GET "${metadata}" location has_gps)
    if(NOT width EQUAL 3 OR NOT height EQUAL 2 OR
       (expect_gps AND NOT gps) OR (NOT expect_gps AND gps))
        message(FATAL_ERROR "JPEG dimensions or GPS changed: ${metadata}")
    endif()
    if(expect_gps)
        string(JSON make GET "${metadata}" camera make)
        string(JSON model GET "${metadata}" camera model)
        string(JSON latitude GET "${metadata}" location latitude)
        string(JSON longitude GET "${metadata}" location longitude)
        execute_process(COMMAND "${PHOTOC}" exif "${source}" --json
            RESULT_VARIABLE source_metadata_exit
            OUTPUT_VARIABLE source_metadata
            ERROR_VARIABLE source_metadata_error)
        if(NOT source_metadata_exit EQUAL 0 OR
           NOT source_metadata_error STREQUAL "")
            message(FATAL_ERROR "Source EXIF unreadable: ${source_metadata_error}")
        endif()
        string(JSON original_latitude GET "${source_metadata}" location latitude)
        string(JSON original_longitude GET "${source_metadata}" location longitude)
        if(NOT make STREQUAL "Fixture Camera Co." OR
           NOT model STREQUAL "Model Z" OR
           NOT latitude STREQUAL original_latitude OR
           NOT longitude STREQUAL original_longitude)
            message(FATAL_ERROR "Camera EXIF changed: ${metadata}")
        endif()
    endif()
    if(CASE STREQUAL "quality_effect")
        file(SHA256 "${output}" low_quality_hash)
        file(REMOVE "${output}")
        execute_process(COMMAND "${PHOTOC}" compress "${source}" --quality 95
            RESULT_VARIABLE high_quality_exit
            OUTPUT_VARIABLE high_quality_stdout
            ERROR_VARIABLE high_quality_stderr)
        if(NOT high_quality_exit EQUAL 0 OR
           NOT high_quality_stderr STREQUAL "" OR NOT EXISTS "${output}")
            message(FATAL_ERROR "High-quality compression failed: ${high_quality_stderr}")
        endif()
        file(SHA256 "${output}" high_quality_hash)
        if(high_quality_hash STREQUAL low_quality_hash)
            message(FATAL_ERROR "JPEG quality did not change output")
        endif()
    endif()
elseif(CASE STREQUAL "collision")
    file(READ "${output}" existing)
    if(NOT existing STREQUAL "sentinel")
        message(FATAL_ERROR "Existing destination overwritten")
    endif()
else()
    if(EXISTS "${output}")
        message(FATAL_ERROR "Unexpected output: ${output}")
    endif()
endif()

file(SHA256 "${root}/photo.jpeg" source_after)
if(CASE STREQUAL "collision" AND NOT source_after STREQUAL original_hash)
    message(FATAL_ERROR "Source changed after collision")
endif()
file(GLOB temporary_files "${root}/*.photoc-*" "${root}/.photoc-exif-*")
if(temporary_files)
    message(FATAL_ERROR "Temporary JPEGs left behind: ${temporary_files}")
endif()
