if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-rename-apply-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
file(MAKE_DIRECTORY "${directory}")
set(format "{original}_{sequence}.{ext}")
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(expect_unchanged FALSE)
set(expected_paths "")

if(CASE STREQUAL "success")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.JpEg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(format "{date}_{camera}_{sequence}.{ext}")
    set(expected_stdout "a.JpEg -> 2024-01-02_Model A_0001.JpEg\nz.jpg -> 2026-09-27_Model Z_0002.jpg\nSummary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 2 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/2024-01-02_Model A_0001.JpEg;photos/2026-09-27_Model Z_0002.jpg")
elseif(CASE STREQUAL "recursive")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/b.JPEG")
    set(expected_stdout "a.jpg -> a_0001.jpg\nnested/b.JPEG -> nested/b_0002.JPEG\nSummary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 2 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/a_0001.jpg;photos/nested;photos/nested/b_0002.JPEG")
elseif(CASE STREQUAL "unchanged")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    set(format "{original}.{ext}")
    set(expected_stdout "a.jpg -> a.jpg (unchanged)\nSummary: 1 JPEG, 0 planned, 1 unchanged, 0 blocked, 0 applied, 0 rolled back\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "empty")
    set(expected_stdout "Summary: 0 JPEG, 0 planned, 0 unchanged, 0 blocked, 0 applied, 0 rolled back\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "collision")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(WRITE "${directory}/taken.txt" "keep this file\n")
    set(format "taken.txt")
    set(expected_exit 1)
    set(expected_stdout "Summary: 1 JPEG, 0 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc rename: 'a.jpg': skipped: destination exists 'taken.txt'\nphotoc rename: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "duplicate")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(format "same.jpg")
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 0 planned, 0 unchanged, 2 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc rename: 'a.jpg': skipped: duplicate destination 'same.jpg'\nphotoc rename: 'b.jpg': skipped: duplicate destination 'same.jpg'\nphotoc rename: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "missing_date")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(format "{date}_{sequence}.{ext}")
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 1 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc rename: 'a.jpg': skipped: missing or invalid metadata for {date}\nphotoc rename: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "invalid_jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 1 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc rename: 'broken.jpg': skipped: invalid or truncated JPEG file\nphotoc rename: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "runtime_rollback")
    execute_process(COMMAND id -u OUTPUT_VARIABLE user_id OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(user_id STREQUAL "0")
        message(STATUS "Skipping permission-based rollback check as root")
        file(REMOVE_RECURSE "${root}")
        return()
    endif()
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/z.jpg")
    file(CHMOD "${directory}/nested" PERMISSIONS OWNER_READ OWNER_EXECUTE)
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 0 applied, 1 rolled back\n")
    set(expect_unchanged TRUE)
else()
    message(FATAL_ERROR "Unknown apply case: ${CASE}")
endif()

file(GLOB_RECURSE before_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT before_paths)
set(before_hashes "")
set(before_content_hashes "")
set(before_files "")
foreach(path IN LISTS before_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND before_hashes "${path}:${hash}")
        list(APPEND before_content_hashes "${hash}")
        list(APPEND before_files "${path}")
    endif()
endforeach()

set(invocation "${PHOTOC}" rename "${directory}" --format "${format}" --apply)
if(CASE STREQUAL "recursive")
    list(APPEND invocation --recursive)
elseif(CASE STREQUAL "runtime_rollback")
    list(APPEND invocation --recursive)
endif()
execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE actual_stdout
    ERROR_VARIABLE actual_stderr
)

file(GLOB_RECURSE after_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT after_paths)
set(after_hashes "")
set(after_content_hashes "")
foreach(path IN LISTS after_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND after_hashes "${path}:${hash}")
        list(APPEND after_content_hashes "${hash}")
    endif()
endforeach()

if(CASE STREQUAL "runtime_rollback")
    file(CHMOD "${directory}/nested" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
endif()

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${actual_stdout}\nstderr: ${actual_stderr}")
endif()
if(NOT actual_stdout STREQUAL expected_stdout)
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${actual_stdout}")
endif()
if(CASE STREQUAL "runtime_rollback")
    set(prefix "photoc rename: apply failed for 'nested/z.jpg' -> 'nested/z_0002.jpg': ")
    string(FIND "${actual_stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR actual_stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected apply failure: ${actual_stderr}")
    endif()
elseif(NOT actual_stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${actual_stderr}")
endif()

if(expect_unchanged)
    if(NOT before_paths STREQUAL after_paths OR NOT before_hashes STREQUAL after_hashes)
        message(FATAL_ERROR "Apply failure or no-op changed the file inventory")
    endif()
else()
    if(NOT after_paths STREQUAL expected_paths)
        message(FATAL_ERROR "Unexpected paths after apply: ${after_paths}")
    endif()
    list(LENGTH before_hashes before_count)
    list(LENGTH after_hashes after_count)
    if(NOT before_count EQUAL after_count)
        message(FATAL_ERROR "Apply changed the number of files")
    endif()
    foreach(path IN LISTS before_files)
        if(EXISTS "${root}/${path}" OR IS_SYMLINK "${root}/${path}")
            message(FATAL_ERROR "Old source path still exists: ${path}")
        endif()
    endforeach()
    list(SORT before_content_hashes)
    list(SORT after_content_hashes)
    if(NOT before_content_hashes STREQUAL after_content_hashes)
        message(FATAL_ERROR "Apply changed file contents")
    endif()
    if(CASE STREQUAL "success")
        file(SHA256 "${FIXTURE_DIR}/with_alt_exif.jpg" expected_alt_hash)
        file(SHA256 "${FIXTURE_DIR}/with_exif.jpg" expected_exif_hash)
        file(SHA256 "${directory}/2024-01-02_Model A_0001.JpEg" actual_alt_hash)
        file(SHA256 "${directory}/2026-09-27_Model Z_0002.jpg" actual_exif_hash)
        if(NOT actual_alt_hash STREQUAL expected_alt_hash OR
           NOT actual_exif_hash STREQUAL expected_exif_hash)
            message(FATAL_ERROR "Applied names do not retain their source contents")
        endif()
    endif()
endif()
file(REMOVE_RECURSE "${root}")
