cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/compress-directory-${CASE}")
file(REMOVE_RECURSE "${root}")
set(source "${root}/photos")
file(MAKE_DIRECTORY "${source}/nested")
file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${source}/a.jpg")
file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${source}/b.jpeg")
file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${source}/nested/c.JPG")
file(WRITE "${source}/note.txt" "not a JPEG")
foreach(name IN ITEMS a.jpg b.jpeg nested/c.JPG)
    file(SHA256 "${source}/${name}" source_hash_${name})
endforeach()

set(arguments compress "${source}" --quality 40)
set(destination "${source}")
set(expected_processed 2)
set(expected_skipped 1)
set(expected_failed 0)
set(expected_exit 0)
if(CASE STREQUAL "recursive")
    list(APPEND arguments --recursive)
    set(expected_processed 3)
elseif(CASE STREQUAL "output_dir")
    set(destination "${source}/export")
    list(APPEND arguments --recursive --output-dir "${destination}")
    set(expected_processed 3)
elseif(CASE STREQUAL "output_dir_external")
    set(destination "${root}/compressed")
    list(APPEND arguments --recursive --output-dir "${destination}")
    set(expected_processed 3)
elseif(CASE STREQUAL "output_dir_same")
    list(APPEND arguments --output-dir "${source}")
elseif(CASE STREQUAL "collision")
    file(WRITE "${source}/a.compressed.jpg" "sentinel")
    set(expected_processed 1)
    set(expected_skipped 3)
elseif(CASE STREQUAL "invalid")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${source}/invalid.jpg")
    set(expected_skipped 1)
    set(expected_failed 1)
    set(expected_exit 1)
elseif(CASE STREQUAL "skipped_inputs")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${source}/prior.compressed.jpg")
    file(CREATE_LINK "${source}/a.jpg" "${source}/link.jpg" SYMBOLIC)
    set(expected_skipped 3)
elseif(CASE STREQUAL "flat")
else()
    message(FATAL_ERROR "Unknown compress directory case: ${CASE}")
endif()

execute_process(COMMAND "${PHOTOC}" ${arguments}
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT exit_code EQUAL expected_exit)
    message(FATAL_ERROR "Exit ${exit_code}, expected ${expected_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(CASE STREQUAL "invalid")
    if(NOT stderr MATCHES "invalid JPEG")
        message(FATAL_ERROR "Missing invalid JPEG diagnostic: ${stderr}")
    endif()
elseif(NOT stderr STREQUAL "")
    message(FATAL_ERROR "Unexpected stderr: ${stderr}")
endif()

set(expected_before 0)
set(expected_after 0)
set(names a.jpg b.jpeg)
if(expected_processed EQUAL 3)
    list(APPEND names nested/c.JPG)
elseif(CASE STREQUAL "collision")
    set(names b.jpeg)
endif()
foreach(name IN LISTS names)
    get_filename_component(parent "${name}" DIRECTORY)
    get_filename_component(stem "${name}" NAME_WE)
    get_filename_component(extension "${name}" EXT)
    if(parent)
        set(output "${destination}/${parent}/${stem}.compressed${extension}")
    else()
        set(output "${destination}/${stem}.compressed${extension}")
    endif()
    if(NOT EXISTS "${output}")
        message(FATAL_ERROR "Missing compressed JPEG: ${output}")
    endif()
    file(SIZE "${source}/${name}" before)
    file(SIZE "${output}" after)
    math(EXPR expected_before "${expected_before} + ${before}")
    math(EXPR expected_after "${expected_after} + ${after}")
    file(SHA256 "${source}/${name}" after_hash)
    if(NOT after_hash STREQUAL source_hash_${name})
        message(FATAL_ERROR "Original changed: ${name}")
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${output}" --json
        RESULT_VARIABLE metadata_exit OUTPUT_VARIABLE metadata ERROR_VARIABLE metadata_error)
    if(NOT metadata_exit EQUAL 0 OR NOT metadata_error STREQUAL "")
        message(FATAL_ERROR "Compressed JPEG unreadable: ${output}: ${metadata_error}")
    endif()
    if(name STREQUAL "a.jpg")
        string(JSON gps GET "${metadata}" location has_gps)
        if(NOT gps)
            message(FATAL_ERROR "GPS EXIF missing from compressed JPEG")
        endif()
    endif()
endforeach()
math(EXPR savings "${expected_before} - ${expected_after}")
foreach(line IN ITEMS
        "Files processed: ${expected_processed}"
        "Files skipped: ${expected_skipped}"
        "Files failed: ${expected_failed}"
        "Bytes before: ${expected_before}"
        "Bytes after: ${expected_after}"
        "Total savings: ${savings} bytes")
    string(FIND "${stdout}" "${line}" found)
    if(found EQUAL -1)
        message(FATAL_ERROR "Missing summary '${line}'\n${stdout}")
    endif()
endforeach()

if(CASE STREQUAL "flat" AND EXISTS "${source}/nested/c.compressed.JPG")
    message(FATAL_ERROR "Flat scan reached nested JPEG")
endif()
if(CASE STREQUAL "skipped_inputs" AND
   (EXISTS "${source}/link.compressed.jpg" OR
    EXISTS "${source}/prior.compressed.compressed.jpg"))
    message(FATAL_ERROR "Symlink or already-compressed JPEG was compressed")
endif()
if(CASE STREQUAL "output_dir" OR CASE STREQUAL "output_dir_external")
    if(EXISTS "${source}/a.compressed.jpg" OR
       EXISTS "${source}/nested/c.compressed.JPG")
        message(FATAL_ERROR "Output unexpectedly written beside source")
    endif()
    execute_process(COMMAND "${PHOTOC}" ${arguments}
        RESULT_VARIABLE repeat_exit OUTPUT_VARIABLE repeat_stdout ERROR_VARIABLE repeat_stderr)
    if(NOT repeat_exit EQUAL 0 OR NOT repeat_stderr STREQUAL "" OR
       NOT repeat_stdout MATCHES "Files processed: 0" OR
       NOT repeat_stdout MATCHES "Files skipped: 4" OR
       NOT repeat_stdout MATCHES "Bytes before: 0" OR
       NOT repeat_stdout MATCHES "Bytes after: 0")
        message(FATAL_ERROR "Repeat run should skip existing outputs: ${repeat_stdout}\n${repeat_stderr}")
    endif()
endif()
if(CASE STREQUAL "collision")
    file(READ "${source}/a.compressed.jpg" sentinel)
    if(NOT sentinel STREQUAL "sentinel")
        message(FATAL_ERROR "Existing output changed")
    endif()
endif()
file(GLOB_RECURSE temporary_files "${root}/*.photoc-*" "${root}/.photoc-*")
if(temporary_files)
    message(FATAL_ERROR "Temporary files left behind: ${temporary_files}")
endif()
