if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(temporary_path "")
if(CASE STREQUAL "with_exif" OR CASE STREQUAL "before_command")
    set(path "${FIXTURE_DIR}/with_exif.jpg")
elseif(CASE STREQUAL "with_gps")
    set(path "${FIXTURE_DIR}/with_gps.jpeg")
elseif(CASE STREQUAL "no_exif")
    set(path "${FIXTURE_DIR}/no_exif.jpg")
elseif(CASE STREQUAL "escaped_path")
    set(path "${CMAKE_CURRENT_BINARY_DIR}/photoc-\"quote\"-back\\slash-\nline-é.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${path}")
    set(temporary_path "${path}")
elseif(CASE STREQUAL "invalid")
    set(path "${FIXTURE_DIR}/invalid.jpg")
elseif(CASE STREQUAL "unsupported")
    set(path "${FIXTURE_DIR}/unsupported.png")
else()
    message(FATAL_ERROR "Unknown JSON test case: ${CASE}")
endif()

if(CASE STREQUAL "before_command")
    set(invocation "${PHOTOC}" --json exif "${path}")
else()
    set(invocation "${PHOTOC}" exif "${path}" --json)
endif()
execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error_output
)
if(NOT temporary_path STREQUAL "")
    file(REMOVE "${temporary_path}")
endif()

if(CASE STREQUAL "invalid" OR CASE STREQUAL "unsupported")
    if(CASE STREQUAL "invalid")
        set(expected_error "invalid or truncated JPEG file")
    else()
        set(expected_error "unsupported file type (expected .jpg or .jpeg)")
    endif()
    if(NOT actual_exit STREQUAL "1" OR NOT output STREQUAL "" OR
       NOT error_output STREQUAL "photoc exif: '${path}': ${expected_error}\n")
        message(FATAL_ERROR "Unexpected JSON error result: ${actual_exit}\n${output}\n${error_output}")
    endif()
    return()
endif()

if(NOT actual_exit STREQUAL "0" OR NOT error_output STREQUAL "")
    message(FATAL_ERROR "JSON command failed: ${actual_exit}\n${error_output}")
endif()

function(check_type expected)
    string(JSON actual ERROR_VARIABLE json_error TYPE "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected ${expected} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

function(check_value expected)
    string(JSON actual ERROR_VARIABLE json_error GET "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected '${expected}' at ${ARGN}; got '${actual}': ${json_error}")
    endif()
endfunction()

function(check_number_range lower upper)
    check_type(NUMBER ${ARGN})
    string(JSON actual ERROR_VARIABLE json_error GET "${output}" ${ARGN})
    if(json_error OR actual LESS lower OR actual GREATER upper)
        message(FATAL_ERROR "Expected number from ${lower} to ${upper} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

check_type(OBJECT)
foreach(section IN ITEMS file image camera exposure date location)
    check_type(OBJECT "${section}")
endforeach()

get_filename_component(filename "${path}" NAME)
file(SIZE "${FIXTURE_DIR}/with_exif.jpg" exif_size)
if(CASE STREQUAL "no_exif")
    file(SIZE "${path}" expected_size)
elseif(CASE STREQUAL "with_gps")
    file(SIZE "${path}" expected_size)
else()
    set(expected_size "${exif_size}")
endif()

check_type(STRING file name)
check_value("${filename}" file name)
check_type(STRING file path)
check_value("${path}" file path)
check_type(NUMBER file size_bytes)
check_value("${expected_size}" file size_bytes)
check_type(NUMBER image width)
check_value("3" image width)
check_type(NUMBER image height)
check_value("2" image height)
check_type(BOOLEAN location has_gps)

if(CASE STREQUAL "no_exif")
    check_type(NULL camera make)
    check_type(NULL camera model)
    check_type(NULL exposure iso)
    check_type(NULL exposure aperture)
    check_type(NULL exposure exposure_time_seconds)
    check_type(NULL exposure focal_length_mm)
    check_type(NULL date captured)
    check_value("OFF" location has_gps)
    check_type(NULL location latitude)
    check_type(NULL location longitude)
else()
    check_type(STRING camera make)
    check_value("Fixture Camera Co." camera make)
    check_type(STRING camera model)
    check_value("Model Z" camera model)
    check_type(NUMBER exposure iso)
    check_value("200" exposure iso)
    check_number_range(2.79999 2.80001 exposure aperture)
    check_number_range(0.007999 0.008001 exposure exposure_time_seconds)
    check_type(NUMBER exposure focal_length_mm)
    check_value("50" exposure focal_length_mm)
    check_type(STRING date captured)
    check_value("2026:09:27 12:34:56" date captured)
    if(CASE STREQUAL "with_gps")
        check_value("ON" location has_gps)
        check_number_range(-37.80834 -37.80832 location latitude)
        check_number_range(-122.40418 -122.40415 location longitude)
    else()
        check_value("OFF" location has_gps)
        check_type(NULL location latitude)
        check_type(NULL location longitude)
    endif()
endif()
