cmake_minimum_required(VERSION 3.21)

if(NOT DEFINED PHOTOC OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC and CASE are required")
endif()

set(invocation "${PHOTOC}")
set(expected_stdout "")
set(expected_stderr "")
set(focus_file "${CMAKE_CURRENT_LIST_DIR}/fixtures/jpeg/flat.jpg")
set(focus_usage "photoc focus: expected exactly one JPEG file or directory\nUsage: photoc focus <file|directory> [--recursive] [--threshold <value>] [--only-blurry] [--json]\n")
file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/focus-flat.txt" focus_output)
string(REPLACE "@PATH@" "${focus_file}" focus_output "${focus_output}")
file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/focus-flat.json" focus_json)
string(REPLACE "@PATH@" "${focus_file}" focus_json "${focus_json}")

if(CASE STREQUAL "help")
    list(APPEND invocation --help)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-global.txt" expected_stdout)
elseif(CASE STREQUAL "short_help")
    list(APPEND invocation -h)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-global.txt" expected_stdout)
elseif(CASE STREQUAL "version")
    list(APPEND invocation --version)
    set(expected_exit 0)
    set(expected_stdout "photoc ${EXPECT_VERSION}\n")
elseif(CASE STREQUAL "short_version")
    list(APPEND invocation -V)
    set(expected_exit 0)
    set(expected_stdout "photoc ${EXPECT_VERSION}\n")
elseif(CASE STREQUAL "no_args")
    set(expected_exit 2)
    set(expected_stderr "photoc: missing command\nUsage: photoc [global options] <command> [args]\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown")
    list(APPEND invocation unknown)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown command 'unknown'\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown_with_option")
    list(APPEND invocation -v unknown)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown command 'unknown'\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown_option_before")
    list(APPEND invocation --bogus compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '--bogus'\nTry 'photoc --help' for available options.\n")
elseif(CASE STREQUAL "unknown_option_after")
    list(APPEND invocation compress --bogus)
    set(expected_exit 2)
    set(expected_stderr "photoc compress: unknown option '--bogus'\nTry 'photoc compress --help' for available options.\n")
elseif(CASE STREQUAL "unknown_short_option")
    list(APPEND invocation -x)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '-x'\nTry 'photoc --help' for available options.\n")
elseif(CASE STREQUAL "help_version_conflict")
    list(APPEND invocation --help --version)
    set(expected_exit 2)
    set(expected_stderr "photoc: --help and --version cannot be used together\n")
elseif(CASE STREQUAL "verbose_quiet_conflict")
    list(APPEND invocation -v -q compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: --verbose and --quiet cannot be used together\n")
elseif(CASE STREQUAL "version_with_command")
    list(APPEND invocation --version compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: --version cannot be used with a command\n")
elseif(CASE STREQUAL "end_of_options")
    list(APPEND invocation -- focus "${focus_file}")
    set(expected_exit 0)
    set(expected_stdout "${focus_output}")
elseif(CASE STREQUAL "end_of_options_command")
    list(APPEND invocation -- --help)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown command '--help'\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "help_before_command")
    list(APPEND invocation --help compress)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-compress.txt" expected_stdout)
elseif(CASE STREQUAL "dash_argument")
    list(APPEND invocation exif -- --not-an-option.jpg)
    set(expected_exit 1)
    set(expected_stderr "photoc exif: '--not-an-option.jpg': file I/O error: unable to read JPEG file: ")
elseif(CASE STREQUAL "focus_json")
    list(APPEND invocation focus "${focus_file}" --json)
    set(expected_exit 0)
    set(expected_stdout "${focus_json}")
elseif(CASE STREQUAL "verbose_quiet_after")
    list(APPEND invocation focus -v -q)
    set(expected_exit 2)
    set(expected_stderr "photoc: --verbose and --quiet cannot be used together\n")
elseif(CASE STREQUAL "command_arguments")
    list(APPEND invocation focus "${focus_file}")
    set(expected_exit 0)
    set(expected_stdout "${focus_output}")
elseif(CASE STREQUAL "focus_usage")
    list(APPEND invocation focus)
    set(expected_exit 2)
    set(expected_stderr "${focus_usage}")
elseif(CASE STREQUAL "stub" AND DEFINED ARG)
    list(APPEND invocation "${ARG}")
    set(expected_exit 3)
    set(expected_stderr "photoc: ${ARG} is not implemented yet\n")
elseif(CASE STREQUAL "command_help" AND DEFINED ARG)
    list(APPEND invocation "${ARG}" --help)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-${ARG}.txt" expected_stdout)
elseif((CASE STREQUAL "option_routing" OR CASE STREQUAL "option_after_routing") AND DEFINED ARG)
    if(CASE STREQUAL "option_routing")
        list(APPEND invocation "${ARG}" focus "${focus_file}")
    else()
        list(APPEND invocation focus "${focus_file}" "${ARG}")
    endif()
    set(expected_exit 0)
    set(expected_stdout "${focus_output}")
    if(ARG STREQUAL "--json")
        set(expected_stdout "${focus_json}")
    elseif(ARG STREQUAL "--quiet" OR ARG STREQUAL "-q")
        string(REPLACE "Files skipped: 0\nFiles failed: 0\n" "" expected_stdout "${expected_stdout}")
        string(REPLACE "Scores are a review aid, not proof of blur or artistic quality.\n" "" expected_stdout "${expected_stdout}")
    elseif(ARG STREQUAL "--verbose" OR ARG STREQUAL "-v")
        set(expected_stderr "photoc focus: verbose: input: ${focus_file}; mode: sharpness; recursive: no; threshold: 100; only blurry: no; output: human\nphotoc focus: verbose: JPEG files discovered: 1; analyzed: 1; skipped: 0; decode failures: 0\n")
    endif()
else()
    message(FATAL_ERROR "Unknown test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()

if(CASE STREQUAL "dash_argument")
    string(FIND "${stderr}" "${expected_stderr}" position)
    if(NOT stdout STREQUAL "" OR NOT position EQUAL 0 OR
       stderr MATCHES "requires a value")
        message(FATAL_ERROR "Unexpected output\nstdout: ${stdout}\nstderr: ${stderr}")
    endif()
elseif(NOT stdout STREQUAL "${expected_stdout}" OR
       NOT stderr STREQUAL "${expected_stderr}")
    message(FATAL_ERROR "Unexpected output\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
