if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-stats-json-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
if(CASE STREQUAL "escaped_directory")
    set(directory "${root}/photos-\"quoted\"-\nline-é")
endif()
file(MAKE_DIRECTORY "${directory}/nested" "${root}/empty" "${root}/missing_exif")
file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${directory}/gps.jpeg")
file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.jpg")
file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/plain.jpg")
file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
file(COPY_FILE "${FIXTURE_DIR}/unsupported.png" "${directory}/graphic.png")
file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/nested/a2.jpg")
file(WRITE "${directory}/notes.txt" "not a photo\n")
file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${root}/missing_exif/one.jpg")

set(invocation "${PHOTOC}" stats "${directory}" --json)
if(CASE STREQUAL "recursive")
    list(APPEND invocation --recursive)
elseif(CASE STREQUAL "empty")
    set(directory "${root}/empty")
    set(invocation "${PHOTOC}" stats "${directory}" --json)
elseif(CASE STREQUAL "missing_exif")
    set(directory "${root}/missing_exif")
    set(invocation "${PHOTOC}" stats "${directory}" --json)
elseif(CASE STREQUAL "before_command")
    set(invocation "${PHOTOC}" --json stats "${directory}")
elseif(CASE STREQUAL "missing")
    set(directory "${root}/missing")
    set(invocation "${PHOTOC}" stats "${directory}" --json)
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error_output
)
file(REMOVE_RECURSE "${root}")

if(CASE STREQUAL "missing")
    if(NOT actual_exit STREQUAL "1" OR NOT output STREQUAL "")
        message(FATAL_ERROR "Unexpected missing-directory result: ${actual_exit}\n${output}\n${error_output}")
    endif()
    set(prefix "photoc stats: '${directory}': ")
    string(FIND "${error_output}" "${prefix}" position)
    if(NOT position EQUAL 0 OR error_output STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected missing-directory diagnostic: ${error_output}")
    endif()
    return()
endif()

if(NOT actual_exit STREQUAL "0")
    message(FATAL_ERROR "JSON command failed: ${actual_exit}\n${error_output}")
endif()
if(CASE STREQUAL "flat" OR CASE STREQUAL "recursive" OR
   CASE STREQUAL "escaped_directory" OR CASE STREQUAL "before_command")
    set(expected_error "photoc stats: warning: '${directory}/broken.jpg': invalid or truncated JPEG file\n")
else()
    set(expected_error "")
endif()
if(NOT error_output STREQUAL expected_error)
    message(FATAL_ERROR "Unexpected stderr: ${error_output}")
endif()

function(check_type expected)
    string(JSON actual ERROR_VARIABLE json_error TYPE "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected ${expected} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

function(check_value expected)
    string(JSON actual ERROR_VARIABLE json_error GET "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected '${expected}' at ${ARGN}; got '${actual}': ${json_error}")
    endif()
endfunction()

function(check_length expected)
    string(JSON actual ERROR_VARIABLE json_error LENGTH "${output}" ${ARGN})
    if(json_error OR NOT actual EQUAL expected)
        message(FATAL_ERROR "Expected length ${expected} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

function(check_entry group index value_type value count percentage)
    check_type(OBJECT distributions ${group} ${index})
    check_type(${value_type} distributions ${group} ${index} value)
    if(value STREQUAL "2.8")
        string(JSON actual GET "${output}" distributions ${group} ${index} value)
        if(actual LESS 2.79999 OR actual GREATER 2.80001)
            message(FATAL_ERROR "Expected aperture near 2.8; got ${actual}")
        endif()
    else()
        check_value("${value}" distributions ${group} ${index} value)
    endif()
    check_type(NUMBER distributions ${group} ${index} count)
    check_value("${count}" distributions ${group} ${index} count)
    check_type(NUMBER distributions ${group} ${index} percentage_of_photos)
    check_value("${percentage}" distributions ${group} ${index} percentage_of_photos)
endfunction()

check_type(OBJECT)
foreach(section IN ITEMS scan storage capture_dates distributions)
    check_type(OBJECT ${section})
endforeach()
check_type(STRING scan directory)
check_value("${directory}" scan directory)
check_type(BOOLEAN scan recursive)
check_type(NUMBER scan files_visited)
check_type(NUMBER scan jpeg_files_found)
check_type(NUMBER scan photos_parsed)
check_type(NUMBER scan skipped_files)
check_type(NUMBER scan errors)
check_type(NUMBER storage total_bytes)
check_type(NUMBER storage photos_with_file_size)

if(CASE STREQUAL "empty" OR CASE STREQUAL "missing_exif")
    check_value("OFF" scan recursive)
    foreach(group IN ITEMS camera_models iso apertures focal_lengths_mm)
        check_type(ARRAY distributions ${group})
        check_length(0 distributions ${group})
    endforeach()
    check_type(NULL capture_dates earliest)
    check_type(NULL capture_dates latest)
    if(CASE STREQUAL "empty")
        check_value("0" scan files_visited)
        check_value("0" scan jpeg_files_found)
        check_value("0" scan photos_parsed)
        check_value("0" storage total_bytes)
        check_value("0" storage photos_with_file_size)
        check_type(NULL storage average_file_size_bytes)
    else()
        file(SIZE "${FIXTURE_DIR}/no_exif.jpg" expected_size)
        check_value("1" scan files_visited)
        check_value("1" scan jpeg_files_found)
        check_value("1" scan photos_parsed)
        check_value("${expected_size}" storage total_bytes)
        check_value("1" storage photos_with_file_size)
        check_type(NUMBER storage average_file_size_bytes)
        check_value("${expected_size}" storage average_file_size_bytes)
    endif()
    check_value("0" scan skipped_files)
    check_value("0" scan errors)
    return()
endif()

file(SIZE "${FIXTURE_DIR}/with_exif.jpg" exif_size)
file(SIZE "${FIXTURE_DIR}/with_gps.jpeg" gps_size)
file(SIZE "${FIXTURE_DIR}/with_alt_exif.jpg" alt_size)
file(SIZE "${FIXTURE_DIR}/no_exif.jpg" bare_size)
math(EXPR expected_size "${exif_size} + ${gps_size} + ${alt_size} + ${bare_size}")
check_type(NUMBER storage average_file_size_bytes)
check_value("3" scan skipped_files)
check_value("1" scan errors)

if(CASE STREQUAL "recursive")
    math(EXPR expected_size "${expected_size} + ${alt_size}")
    check_value("ON" scan recursive)
    check_value("8" scan files_visited)
    check_value("6" scan jpeg_files_found)
    check_value("5" scan photos_parsed)
    check_value("${expected_size}" storage total_bytes)
    check_value("5" storage photos_with_file_size)
else()
    check_value("OFF" scan recursive)
    check_value("7" scan files_visited)
    check_value("5" scan jpeg_files_found)
    check_value("4" scan photos_parsed)
    check_value("${expected_size}" storage total_bytes)
    check_value("4" storage photos_with_file_size)
endif()
check_type(STRING capture_dates earliest)
check_value("2024:01:02 03:04:05" capture_dates earliest)
check_type(STRING capture_dates latest)
check_value("2026:09:27 12:34:56" capture_dates latest)

foreach(group IN ITEMS camera_models iso apertures focal_lengths_mm)
    check_type(ARRAY distributions ${group})
    check_length(2 distributions ${group})
endforeach()
if(CASE STREQUAL "recursive")
    check_entry(camera_models 0 STRING "Model A" 2 40)
    check_entry(camera_models 1 STRING "Model Z" 2 40)
    check_entry(iso 0 NUMBER 100 2 40)
    check_entry(iso 1 NUMBER 200 2 40)
    check_entry(apertures 0 NUMBER 2.8 2 40)
    check_entry(apertures 1 NUMBER 4 2 40)
    check_entry(focal_lengths_mm 0 NUMBER 35 2 40)
    check_entry(focal_lengths_mm 1 NUMBER 50 2 40)
else()
    check_entry(camera_models 0 STRING "Model Z" 2 50)
    check_entry(camera_models 1 STRING "Model A" 1 25)
    check_entry(iso 0 NUMBER 200 2 50)
    check_entry(iso 1 NUMBER 100 1 25)
    check_entry(apertures 0 NUMBER 2.8 2 50)
    check_entry(apertures 1 NUMBER 4 1 25)
    check_entry(focal_lengths_mm 0 NUMBER 50 2 50)
    check_entry(focal_lengths_mm 1 NUMBER 35 1 25)
endif()
