if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-stats-${CASE}")
file(REMOVE_RECURSE "${root}")
set(DIRECTORY "${root}/photos")
file(MAKE_DIRECTORY "${DIRECTORY}/nested" "${root}/empty"
     "${root}/single" "${root}/missing_exif")
file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${DIRECTORY}/z.jpg")
file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${DIRECTORY}/gps.jpeg")
file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${DIRECTORY}/a.jpg")
file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${DIRECTORY}/plain.jpg")
file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${DIRECTORY}/broken.jpg")
file(COPY_FILE "${FIXTURE_DIR}/unsupported.png" "${DIRECTORY}/graphic.png")
file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${DIRECTORY}/nested/a2.jpg")
file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${root}/single/one.jpg")
file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${root}/missing_exif/one.jpg")
file(WRITE "${DIRECTORY}/notes.txt" "not a photo\n")

set(invocation "${PHOTOC}" stats)
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(check_io_error FALSE)

if(CASE STREQUAL "flat" OR CASE STREQUAL "recursive")
    list(APPEND invocation "${DIRECTORY}")
    if(CASE STREQUAL "recursive")
        list(APPEND invocation --recursive)
    endif()
    file(SIZE "${FIXTURE_DIR}/with_exif.jpg" exif_size)
    file(SIZE "${FIXTURE_DIR}/with_gps.jpeg" gps_size)
    file(SIZE "${FIXTURE_DIR}/with_alt_exif.jpg" alt_size)
    file(SIZE "${FIXTURE_DIR}/no_exif.jpg" bare_size)
    math(EXPR TOTAL_SIZE "${exif_size} + ${gps_size} + ${alt_size} + ${bare_size}")
    if(CASE STREQUAL "recursive")
        math(EXPR TOTAL_SIZE "${TOTAL_SIZE} + ${alt_size}")
    endif()
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/stats-${CASE}.txt" snapshot)
    string(CONFIGURE "${snapshot}" expected_stdout @ONLY)
    set(expected_stderr "photoc stats: warning: '${DIRECTORY}/broken.jpg': invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "empty")
    set(DIRECTORY "${root}/empty")
    list(APPEND invocation "${DIRECTORY}")
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/stats-empty.txt" snapshot)
    string(CONFIGURE "${snapshot}" expected_stdout @ONLY)
elseif(CASE STREQUAL "single" OR CASE STREQUAL "missing_exif")
    set(DIRECTORY "${root}/${CASE}")
    list(APPEND invocation "${DIRECTORY}")
    file(SIZE "${DIRECTORY}/one.jpg" TOTAL_SIZE)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/stats-${CASE}.txt" snapshot)
    string(CONFIGURE "${snapshot}" expected_stdout @ONLY)
elseif(CASE STREQUAL "missing")
    set(DIRECTORY "${root}/missing")
    list(APPEND invocation "${DIRECTORY}")
    set(expected_exit 1)
    set(check_io_error TRUE)
elseif(CASE STREQUAL "no_argument")
    set(expected_exit 2)
    set(expected_stderr "photoc stats: expected exactly one directory\nUsage: photoc stats <directory> [--recursive] [--json]\n")
elseif(CASE STREQUAL "extra_argument")
    list(APPEND invocation "${DIRECTORY}" "${root}/empty")
    set(expected_exit 2)
    set(expected_stderr "photoc stats: expected exactly one directory\nUsage: photoc stats <directory> [--recursive] [--json]\n")
elseif(CASE STREQUAL "unknown_option")
    list(APPEND invocation "${DIRECTORY}" --bogus)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '--bogus'\nTry 'photoc --help' for available options.\n")
else()
    message(FATAL_ERROR "Unknown stats test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)
file(REMOVE_RECURSE "${root}")

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(NOT stdout STREQUAL "${expected_stdout}")
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${stdout}")
endif()
if(check_io_error)
    set(prefix "photoc stats: '${DIRECTORY}': ")
    string(FIND "${stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected I/O error: ${stderr}")
    endif()
elseif(NOT stderr STREQUAL "${expected_stderr}")
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${stderr}")
endif()
