if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/compress-target-${CASE}")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")
set(fixture "${FIXTURE_DIR}/no_exif.jpg")
if(CASE STREQUAL "reachable_exif")
    set(fixture "${FIXTURE_DIR}/with_gps.jpeg")
endif()
set(source "${root}/photo.jpg")
set(output "${root}/photo.compressed.jpg")
file(COPY_FILE "${fixture}" "${source}")
file(SHA256 "${source}" original_hash)

set(expected_exit 0)
set(expected_error "")
set(expect_output TRUE)
set(arguments compress "${source}")
if(CASE STREQUAL "reachable" OR CASE STREQUAL "reachable_exif")
    file(COPY_FILE "${fixture}" "${root}/baseline.jpg")
    execute_process(COMMAND "${PHOTOC}" compress "${root}/baseline.jpg" --quality 60
        RESULT_VARIABLE baseline_exit ERROR_VARIABLE baseline_error)
    if(NOT baseline_exit EQUAL 0 OR NOT baseline_error STREQUAL "")
        message(FATAL_ERROR "Could not produce baseline JPEG: ${baseline_error}")
    endif()
    file(SIZE "${root}/baseline.compressed.jpg" target_size)
    list(APPEND arguments --target "${target_size}B")
elseif(CASE STREQUAL "unreachable")
    list(APPEND arguments --target 1B --min-quality 70)
    set(expected_exit 1)
    set(expected_error "target cannot be reached without going below minimum quality 70")
elseif(CASE STREQUAL "max_fits")
    list(APPEND arguments --target 2MB)
elseif(CASE STREQUAL "collision")
    file(WRITE "${output}" "sentinel")
    list(APPEND arguments --target 2MB)
    set(expected_exit 1)
    set(expected_error "collision: output already exists")
    set(expect_output FALSE)
elseif(CASE STREQUAL "quality_conflict")
    list(APPEND arguments --target 2MB --quality 50)
    set(expected_exit 2)
    set(expected_error "--quality and --target cannot be combined")
    set(expect_output FALSE)
elseif(CASE STREQUAL "min_without_target")
    list(APPEND arguments --min-quality 40)
    set(expected_exit 2)
    set(expected_error "--min-quality requires --target")
    set(expect_output FALSE)
elseif(CASE STREQUAL "invalid_target")
    list(APPEND arguments --target 1.5MB)
    set(expected_exit 2)
    set(expected_error "invalid target")
    set(expect_output FALSE)
elseif(CASE STREQUAL "invalid_min")
    list(APPEND arguments --target 2MB --min-quality 0)
    set(expected_exit 2)
    set(expected_error "invalid minimum quality")
    set(expect_output FALSE)
elseif(CASE STREQUAL "missing_target")
    list(APPEND arguments --target)
    set(expected_exit 2)
    set(expected_error "option '--target' requires a value")
    set(expect_output FALSE)
elseif(CASE STREQUAL "duplicate_target")
    list(APPEND arguments --target 1MB --target 2MB)
    set(expected_exit 2)
    set(expected_error "option '--target' may be specified only once")
    set(expect_output FALSE)
elseif(CASE STREQUAL "directory")
    set(source "${root}/photos")
    set(destination "${root}/output")
    file(MAKE_DIRECTORY "${source}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${source}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${source}/nested/b.jpg")
    file(SHA256 "${source}/a.jpg" directory_a_hash)
    file(SHA256 "${source}/nested/b.jpg" directory_b_hash)
    set(arguments compress "${source}" --recursive --target 2MB
                  --output-dir "${destination}")
else()
    message(FATAL_ERROR "Unknown target case: ${CASE}")
endif()

execute_process(COMMAND "${PHOTOC}" ${arguments}
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT exit_code EQUAL expected_exit)
    message(FATAL_ERROR "Exit ${exit_code}, expected ${expected_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(expected_error AND NOT stderr MATCHES "${expected_error}")
    message(FATAL_ERROR "Missing diagnostic: ${stderr}")
endif()
if(NOT expected_error AND NOT stderr STREQUAL "")
    message(FATAL_ERROR "Unexpected stderr: ${stderr}")
endif()

if(CASE STREQUAL "directory")
    foreach(name IN ITEMS a.jpg nested/b.jpg)
        get_filename_component(parent "${name}" DIRECTORY)
        get_filename_component(stem "${name}" NAME_WE)
        set(created "${destination}/${parent}/${stem}.compressed.jpg")
        if(NOT EXISTS "${created}")
            message(FATAL_ERROR "Missing directory output: ${created}")
        endif()
        execute_process(COMMAND "${PHOTOC}" exif "${created}" --json
            RESULT_VARIABLE metadata_exit OUTPUT_VARIABLE metadata)
        if(NOT metadata_exit EQUAL 0)
            message(FATAL_ERROR "Directory output is not valid JPEG: ${created}")
        endif()
    endforeach()
    file(SHA256 "${source}/a.jpg" directory_a_after)
    file(SHA256 "${source}/nested/b.jpg" directory_b_after)
    if(NOT directory_a_after STREQUAL directory_a_hash OR
       NOT directory_b_after STREQUAL directory_b_hash)
        message(FATAL_ERROR "Directory source JPEG changed")
    endif()
    if(NOT stdout MATCHES "Files processed: 2" OR
       NOT stdout MATCHES "Files failed: 0" OR
       NOT stdout MATCHES "Targets not met: 0" OR
       NOT stdout MATCHES "quality 100")
        message(FATAL_ERROR "Incorrect directory target report: ${stdout}")
    endif()
    return()
endif()

file(SHA256 "${source}" after_hash)
if(NOT after_hash STREQUAL original_hash)
    message(FATAL_ERROR "Original JPEG changed")
endif()
if(expect_output)
    if(NOT EXISTS "${output}")
        message(FATAL_ERROR "Expected output: ${output}")
    endif()
    file(SIZE "${output}" actual_size)
    if(NOT stdout MATCHES "Compressed size: ${actual_size} bytes" OR
       NOT stdout MATCHES "Quality: ([0-9]+)")
        message(FATAL_ERROR "Missing achieved size or quality: ${stdout}")
    endif()
    set(achieved_quality "${CMAKE_MATCH_1}")
    if(CASE STREQUAL "reachable" OR CASE STREQUAL "reachable_exif")
        if(actual_size GREATER target_size OR achieved_quality LESS 60 OR
           NOT stdout MATCHES "Target met: yes")
            message(FATAL_ERROR "Search missed reachable target: ${stdout}")
        endif()
        if(achieved_quality LESS 100)
            math(EXPR next_quality "${achieved_quality} + 1")
            file(COPY_FILE "${fixture}" "${root}/next.jpg")
            execute_process(COMMAND "${PHOTOC}" compress "${root}/next.jpg"
                            --quality "${next_quality}"
                RESULT_VARIABLE next_exit ERROR_VARIABLE next_error)
            if(NOT next_exit EQUAL 0 OR NOT next_error STREQUAL "")
                message(FATAL_ERROR "Could not encode next quality: ${next_error}")
            endif()
            file(SIZE "${root}/next.compressed.jpg" next_size)
            if(NOT next_size GREATER target_size)
                message(FATAL_ERROR "Higher quality ${next_quality} also fits target")
            endif()
        endif()
    elseif(CASE STREQUAL "unreachable")
        if(NOT achieved_quality EQUAL 70 OR
           NOT stdout MATCHES "Target met: no")
            message(FATAL_ERROR "Unreachable target report incorrect: ${stdout}")
        endif()
    elseif(CASE STREQUAL "max_fits")
        if(NOT achieved_quality EQUAL 100 OR
           NOT stdout MATCHES "Target met: yes")
            message(FATAL_ERROR "Expected quality 100: ${stdout}")
        endif()
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${output}" --json
        RESULT_VARIABLE metadata_exit OUTPUT_VARIABLE metadata
        ERROR_VARIABLE metadata_error)
    if(NOT metadata_exit EQUAL 0 OR NOT metadata_error STREQUAL "")
        message(FATAL_ERROR "Compressed output unreadable: ${metadata_error}")
    endif()
    if(CASE STREQUAL "reachable_exif")
        string(JSON gps GET "${metadata}" location has_gps)
        if(NOT gps)
            message(FATAL_ERROR "GPS EXIF missing from target output")
        endif()
    endif()
elseif(CASE STREQUAL "collision")
    file(READ "${output}" existing)
    if(NOT existing STREQUAL "sentinel")
        message(FATAL_ERROR "Existing output was overwritten")
    endif()
elseif(EXISTS "${output}")
    message(FATAL_ERROR "Unexpected output: ${output}")
endif()
