if(NOT DEFINED PHOTOC OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC and CASE are required")
endif()

set(invocation "${PHOTOC}")
set(expected_stdout "")
set(expected_stderr "")

if(CASE STREQUAL "help")
    list(APPEND invocation --help)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-global.txt" expected_stdout)
elseif(CASE STREQUAL "short_help")
    list(APPEND invocation -h)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-global.txt" expected_stdout)
elseif(CASE STREQUAL "version")
    list(APPEND invocation --version)
    set(expected_exit 0)
    set(expected_stdout "photoc ${EXPECT_VERSION}\n")
elseif(CASE STREQUAL "short_version")
    list(APPEND invocation -V)
    set(expected_exit 0)
    set(expected_stdout "photoc ${EXPECT_VERSION}\n")
elseif(CASE STREQUAL "no_args")
    set(expected_exit 2)
    set(expected_stderr "photoc: missing command\nUsage: photoc [global options] <command> [args]\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown")
    list(APPEND invocation unknown)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown command 'unknown'\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown_with_option")
    list(APPEND invocation -v unknown)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown command 'unknown'\nTry 'photoc --help' for available commands.\n")
elseif(CASE STREQUAL "unknown_option_before")
    list(APPEND invocation --bogus compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '--bogus'\nTry 'photoc --help' for available options.\n")
elseif(CASE STREQUAL "unknown_option_after")
    list(APPEND invocation compress --bogus)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '--bogus'\nTry 'photoc --help' for available options.\n")
elseif(CASE STREQUAL "unknown_short_option")
    list(APPEND invocation -x)
    set(expected_exit 2)
    set(expected_stderr "photoc: unknown option '-x'\nTry 'photoc --help' for available options.\n")
elseif(CASE STREQUAL "help_version_conflict")
    list(APPEND invocation --help --version)
    set(expected_exit 2)
    set(expected_stderr "photoc: --help and --version cannot be used together\n")
elseif(CASE STREQUAL "verbose_quiet_conflict")
    list(APPEND invocation -v -q compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: --verbose and --quiet cannot be used together\n")
elseif(CASE STREQUAL "version_with_command")
    list(APPEND invocation --version compress)
    set(expected_exit 2)
    set(expected_stderr "photoc: --version cannot be used with a command\n")
elseif(CASE STREQUAL "end_of_options")
    list(APPEND invocation -- compress)
    set(expected_exit 3)
    set(expected_stderr "photoc: compress is not implemented yet\n")
elseif(CASE STREQUAL "command_arguments")
    list(APPEND invocation compress photo.jpg)
    set(expected_exit 3)
    set(expected_stderr "photoc: compress is not implemented yet\n")
elseif(CASE STREQUAL "stub" AND DEFINED ARG)
    list(APPEND invocation "${ARG}")
    set(expected_exit 3)
    set(expected_stderr "photoc: ${ARG} is not implemented yet\n")
elseif(CASE STREQUAL "command_help" AND DEFINED ARG)
    list(APPEND invocation "${ARG}" --help)
    set(expected_exit 0)
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/help-${ARG}.txt" expected_stdout)
elseif(CASE STREQUAL "option_routing" AND DEFINED ARG)
    list(APPEND invocation "${ARG}" compress)
    set(expected_exit 3)
    set(expected_stderr "photoc: compress is not implemented yet\n")
elseif(CASE STREQUAL "option_after_routing" AND DEFINED ARG)
    list(APPEND invocation compress "${ARG}")
    set(expected_exit 3)
    set(expected_stderr "photoc: compress is not implemented yet\n")
else()
    message(FATAL_ERROR "Unknown test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()

if(NOT stdout STREQUAL "${expected_stdout}" OR
   NOT stderr STREQUAL "${expected_stderr}")
    message(FATAL_ERROR "Unexpected output\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
