if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/scrub-cli-${CASE}")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")
set(gps "${root}/gps.jpeg")
set(clean "${root}/clean.jpg")
set(invalid "${root}/invalid.jpg")
file(COPY_FILE "${FIXTURE_DIR}/with_gps.jpeg" "${gps}")
file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${clean}")
file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${invalid}")
file(SHA256 "${gps}" original_hash)

set(arguments)
set(expected_exit 0)
set(expected_summary "")
set(expected_error "")

if(CASE STREQUAL "single")
    set(arguments scrub "${gps}" --gps)
    set(expected_summary "Files processed: 1\nFiles skipped: 0\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "directory")
    file(REMOVE "${invalid}")
    file(WRITE "${root}/notes.txt" "not a JPEG")
    set(arguments scrub "${root}" --gps)
    set(expected_summary "Files processed: 1\nFiles skipped: 2\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "directory_failure")
    set(arguments scrub "${root}" --gps)
    set(expected_exit 1)
    set(expected_summary "Files processed: 1\nFiles skipped: 1\nFiles failed: 1\nFiles with GPS found and removed: 1")
    set(expected_error "invalid JPEG")
elseif(CASE STREQUAL "symlink")
    file(REMOVE "${invalid}")
    file(REMOVE "${clean}")
    file(CREATE_LINK "${gps}" "${root}/link.jpeg" SYMBOLIC)
    file(WRITE "${root}/notes.txt" "not a JPEG")
    set(arguments scrub "${root}" --gps)
    set(expected_summary "Files processed: 1\nFiles skipped: 2\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "recursive")
    file(REMOVE "${invalid}")
    file(MAKE_DIRECTORY "${root}/nested")
    file(RENAME "${gps}" "${root}/nested/gps.jpeg")
    set(gps "${root}/nested/gps.jpeg")
    file(SHA256 "${gps}" original_hash)
    set(arguments scrub "${root}" --gps --recursive)
    set(expected_summary "Files processed: 1\nFiles skipped: 1\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "in_place_single")
    file(WRITE "${root}/gps.scrubbed.jpeg" "sentinel")
    set(arguments scrub "${gps}" --gps --in-place)
    set(expected_summary "Files processed: 1\nFiles skipped: 0\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "in_place_directory")
    file(REMOVE "${invalid}")
    set(arguments scrub "${root}" --gps --in-place)
    set(expected_summary "Files processed: 1\nFiles skipped: 1\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "in_place_directory_failure")
    set(arguments scrub "${root}" --gps --in-place)
    set(expected_exit 1)
    set(expected_summary "Files processed: 1\nFiles skipped: 1\nFiles failed: 1\nFiles with GPS found and removed: 1")
    set(expected_error "invalid JPEG")
elseif(CASE STREQUAL "in_place_recursive")
    file(REMOVE "${invalid}")
    file(MAKE_DIRECTORY "${root}/nested")
    file(RENAME "${gps}" "${root}/nested/gps.jpeg")
    set(gps "${root}/nested/gps.jpeg")
    file(SHA256 "${gps}" original_hash)
    set(arguments scrub "${root}" --gps --recursive --in-place)
    set(expected_summary "Files processed: 1\nFiles skipped: 1\nFiles failed: 0\nFiles with GPS found and removed: 1")
elseif(CASE STREQUAL "in_place_no_gps")
    set(arguments scrub "${clean}" --gps --in-place)
    set(expected_summary "Files processed: 0\nFiles skipped: 1\nFiles failed: 0\nFiles with GPS found and removed: 0")
elseif(CASE STREQUAL "in_place_invalid")
    set(arguments scrub "${invalid}" --gps --in-place)
    set(expected_exit 1)
    set(expected_summary "Files processed: 0\nFiles skipped: 0\nFiles failed: 1\nFiles with GPS found and removed: 0")
    set(expected_error "invalid JPEG")
elseif(CASE STREQUAL "in_place_hardlink")
    file(CREATE_LINK "${gps}" "${root}/linked.jpeg")
    set(arguments scrub "${gps}" --gps --in-place)
    set(expected_exit 1)
    set(expected_summary "Files processed: 0\nFiles skipped: 0\nFiles failed: 1\nFiles with GPS found and removed: 0")
    set(expected_error "unsafe in-place source")
elseif(CASE STREQUAL "in_place_symlink")
    file(CREATE_LINK "${gps}" "${root}/symlink.jpeg" SYMBOLIC)
    set(arguments scrub "${root}/symlink.jpeg" --gps --in-place)
    set(expected_exit 1)
    set(expected_error "expected a regular JPEG file or directory")
elseif(CASE STREQUAL "no_gps")
    set(arguments scrub "${clean}" --gps)
    set(expected_summary "Files processed: 0\nFiles skipped: 1\nFiles failed: 0\nFiles with GPS found and removed: 0")
elseif(CASE STREQUAL "invalid")
    set(arguments scrub "${invalid}" --gps)
    set(expected_exit 1)
    set(expected_summary "Files processed: 0\nFiles skipped: 0\nFiles failed: 1\nFiles with GPS found and removed: 0")
    set(expected_error "invalid JPEG")
elseif(CASE STREQUAL "collision")
    file(WRITE "${root}/gps.scrubbed.jpeg" "sentinel")
    set(arguments scrub "${gps}" --gps)
    set(expected_exit 1)
    set(expected_summary "Files processed: 0\nFiles skipped: 0\nFiles failed: 1\nFiles with GPS found and removed: 0")
    set(expected_error "collision: output already exists")
elseif(CASE STREQUAL "unsupported")
    file(COPY_FILE "${FIXTURE_DIR}/unsupported.png" "${root}/picture.png")
    set(arguments scrub "${root}/picture.png" --gps)
    set(expected_exit 1)
    set(expected_error "expected a regular JPEG file or directory")
elseif(CASE STREQUAL "missing_gps")
    set(arguments scrub "${gps}")
    set(expected_exit 2)
    set(expected_error "expected one file or directory and --gps")
elseif(CASE STREQUAL "missing_path")
    set(arguments scrub "${root}/absent.jpg" --gps)
    set(expected_exit 1)
    set(expected_error "No such file or directory")
elseif(CASE STREQUAL "recursive_file")
    set(arguments scrub "${gps}" --gps --recursive)
    set(expected_exit 2)
    set(expected_error "--recursive requires a directory")
elseif(CASE STREQUAL "json")
    set(arguments scrub "${gps}" --gps --json)
    set(expected_exit 2)
    set(expected_error "--json is not supported")
elseif(CASE STREQUAL "unknown_option")
    set(arguments scrub "${gps}" --gps --bogus)
    set(expected_exit 2)
    set(expected_error "unknown option '--bogus'")
else()
    message(FATAL_ERROR "Unknown scrub case: ${CASE}")
endif()

execute_process(COMMAND "${PHOTOC}" ${arguments}
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(NOT "${exit_code}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Exit ${exit_code}, expected ${expected_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(expected_summary AND NOT stdout MATCHES "${expected_summary}")
    message(FATAL_ERROR "Missing summary\nstdout: ${stdout}")
endif()
if(expected_error AND NOT stderr MATCHES "${expected_error}")
    message(FATAL_ERROR "Missing diagnostic\nstderr: ${stderr}")
endif()
if(expected_exit EQUAL 0 AND NOT stderr STREQUAL "")
    message(FATAL_ERROR "Unexpected stderr: ${stderr}")
endif()

if(CASE STREQUAL "single" OR CASE STREQUAL "directory" OR
   CASE STREQUAL "directory_failure" OR CASE STREQUAL "symlink" OR
   CASE STREQUAL "recursive")
    string(REGEX REPLACE "\\.(jpe?g)$" ".scrubbed.\\1" output "${gps}")
    if(NOT EXISTS "${output}")
        message(FATAL_ERROR "Scrubbed JPEG missing: ${output}")
    endif()
    if(NOT stdout MATCHES "GPS removed: ${gps} -> ${output}")
        message(FATAL_ERROR "Missing per-file GPS removal output: ${stdout}")
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${output}" --json
        RESULT_VARIABLE exif_exit OUTPUT_VARIABLE metadata ERROR_VARIABLE exif_error)
    if(NOT exif_exit EQUAL 0 OR NOT exif_error STREQUAL "")
        message(FATAL_ERROR "Output JPEG unreadable: ${exif_error}")
    endif()
    string(JSON make GET "${metadata}" camera make)
    string(JSON model GET "${metadata}" camera model)
    string(JSON width GET "${metadata}" image width)
    string(JSON height GET "${metadata}" image height)
    string(JSON has_gps GET "${metadata}" location has_gps)
    if(NOT make STREQUAL "Fixture Camera Co." OR
       NOT model STREQUAL "Model Z" OR
       NOT width EQUAL 3 OR NOT height EQUAL 2 OR has_gps)
        message(FATAL_ERROR "Scrubbed metadata incorrect: ${metadata}")
    endif()
    file(SHA256 "${gps}" after_hash)
    if(NOT after_hash STREQUAL original_hash)
        message(FATAL_ERROR "Original JPEG changed")
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${gps}" --json
        RESULT_VARIABLE original_exit OUTPUT_VARIABLE original_metadata)
    string(JSON original_gps GET "${original_metadata}" location has_gps)
    if(NOT original_exit EQUAL 0 OR NOT original_gps)
        message(FATAL_ERROR "Original GPS metadata changed")
    endif()
    if(EXISTS "${root}/gps.scrubbed.scrubbed.jpeg" OR
       EXISTS "${root}/nested/gps.scrubbed.scrubbed.jpeg" OR
       EXISTS "${root}/link.scrubbed.jpeg")
        message(FATAL_ERROR "Scrubbed output was processed again")
    endif()
elseif(CASE STREQUAL "no_gps")
    if(EXISTS "${root}/clean.scrubbed.jpg")
        message(FATAL_ERROR "No-GPS JPEG should not produce a copy")
    endif()
elseif(CASE STREQUAL "collision")
    file(READ "${root}/gps.scrubbed.jpeg" existing)
    if(NOT existing STREQUAL "sentinel")
        message(FATAL_ERROR "Existing destination was overwritten")
    endif()
    file(SHA256 "${gps}" after_hash)
    if(NOT after_hash STREQUAL original_hash)
        message(FATAL_ERROR "Original JPEG changed after collision")
    endif()
endif()

if(CASE MATCHES "^in_place_(single|directory|directory_failure|recursive)$")
    if(NOT stdout MATCHES "GPS removed in place: ${gps}")
        message(FATAL_ERROR "Missing in-place result: ${stdout}")
    endif()
    execute_process(COMMAND "${PHOTOC}" exif "${gps}" --json
        RESULT_VARIABLE exif_exit OUTPUT_VARIABLE metadata ERROR_VARIABLE exif_error)
    if(NOT exif_exit EQUAL 0 OR NOT exif_error STREQUAL "")
        message(FATAL_ERROR "In-place JPEG unreadable: ${exif_error}")
    endif()
    string(JSON make GET "${metadata}" camera make)
    string(JSON model GET "${metadata}" camera model)
    string(JSON width GET "${metadata}" image width)
    string(JSON height GET "${metadata}" image height)
    string(JSON has_gps GET "${metadata}" location has_gps)
    if(NOT make STREQUAL "Fixture Camera Co." OR
       NOT model STREQUAL "Model Z" OR
       NOT width EQUAL 3 OR NOT height EQUAL 2 OR has_gps)
        message(FATAL_ERROR "In-place JPEG metadata incorrect: ${metadata}")
    endif()
    file(SHA256 "${gps}" after_hash)
    if(after_hash STREQUAL original_hash)
        message(FATAL_ERROR "In-place JPEG was not changed")
    endif()
    if(CASE STREQUAL "in_place_single")
        file(READ "${root}/gps.scrubbed.jpeg" existing)
        if(NOT existing STREQUAL "sentinel")
            message(FATAL_ERROR "Unrelated copy destination changed")
        endif()
    elseif(EXISTS "${root}/gps.scrubbed.jpeg" OR
           EXISTS "${root}/nested/gps.scrubbed.jpeg")
        message(FATAL_ERROR "In-place mode created an unwanted copy")
    endif()
elseif(CASE STREQUAL "in_place_hardlink" OR
       CASE STREQUAL "in_place_symlink")
    file(SHA256 "${gps}" after_hash)
    if(NOT after_hash STREQUAL original_hash)
        message(FATAL_ERROR "Unsafe source changed")
    endif()
endif()

file(GLOB leftover_temporaries "${root}/.photoc-exif-*"
     "${root}/nested/.photoc-exif-*")
if(leftover_temporaries)
    message(FATAL_ERROR "Temporary JPEGs were left behind: ${leftover_temporaries}")
endif()
