if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-sort-apply-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
file(MAKE_DIRECTORY "${directory}")
set(mode date)
set(extra_args "")
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(expected_paths "")
set(mappings "")
set(expect_unchanged FALSE)
set(error_prefix "")

if(CASE STREQUAL "date_success")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.JpEg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(expected_stdout "a.JpEg -> 2024/01/02/a.JpEg\nz.jpg -> 2026/09/27/z.jpg\nSummary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 2 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/2024;photos/2024/01;photos/2024/01/02;photos/2024/01/02/a.JpEg;photos/2026;photos/2026/09;photos/2026/09/27;photos/2026/09/27/z.jpg")
    set(mappings "photos/a.JpEg|photos/2024/01/02/a.JpEg;photos/z.jpg|photos/2026/09/27/z.jpg")
elseif(CASE STREQUAL "date_recursive")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/z.JPEG")
    list(APPEND extra_args --recursive)
    set(expected_stdout "a.jpg -> 2024/01/02/a.jpg\nnested/z.JPEG -> 2026/09/27/z.JPEG\nSummary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 2 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/2024;photos/2024/01;photos/2024/01/02;photos/2024/01/02/a.jpg;photos/2026;photos/2026/09;photos/2026/09/27;photos/2026/09/27/z.JPEG;photos/nested")
    set(mappings "photos/a.jpg|photos/2024/01/02/a.jpg;photos/nested/z.JPEG|photos/2026/09/27/z.JPEG")
elseif(CASE STREQUAL "session_success")
    set(mode session)
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/a.JPEG")
    file(COPY_FILE "${FIXTURE_DIR}/session_1200.jpg" "${directory}/b.jpg")
    list(APPEND extra_args --gap 30m)
    set(expected_stdout "a.JPEG -> session-001/a.JPEG\nb.jpg -> session-002/b.jpg\nz.jpg -> session-001/z.jpg\nSummary: 3 JPEG, 3 planned, 0 unchanged, 0 blocked, 3 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/session-001;photos/session-001/a.JPEG;photos/session-001/z.jpg;photos/session-002;photos/session-002/b.jpg")
    set(mappings "photos/a.JPEG|photos/session-001/a.JPEG;photos/b.jpg|photos/session-002/b.jpg;photos/z.jpg|photos/session-001/z.jpg")
elseif(CASE STREQUAL "session_recursive")
    set(mode session)
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/session_1200.jpg" "${directory}/nested/b.jpg")
    list(APPEND extra_args --recursive)
    set(expected_stdout "nested/b.jpg -> session-002/b.jpg\nz.jpg -> session-001/z.jpg\nSummary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 2 applied, 0 rolled back\n")
    set(expected_paths "photos;photos/nested;photos/session-001;photos/session-001/z.jpg;photos/session-002;photos/session-002/b.jpg")
    set(mappings "photos/nested/b.jpg|photos/session-002/b.jpg;photos/z.jpg|photos/session-001/z.jpg")
elseif(CASE STREQUAL "unchanged")
    file(MAKE_DIRECTORY "${directory}/2026/09/27")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/2026/09/27/a.jpg")
    list(APPEND extra_args --recursive)
    set(expected_stdout "2026/09/27/a.jpg -> 2026/09/27/a.jpg (unchanged)\nSummary: 1 JPEG, 0 planned, 1 unchanged, 0 blocked, 0 applied, 0 rolled back\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "empty")
    set(expected_stdout "Summary: 0 JPEG, 0 planned, 0 unchanged, 0 blocked, 0 applied, 0 rolled back\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "collision")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/2026/09/27")
    file(WRITE "${directory}/2026/09/27/a.jpg" "keep this file\n")
    set(expected_exit 1)
    set(expected_stdout "Summary: 1 JPEG, 0 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: destination exists '2026/09/27/a.jpg'\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "duplicate")
    set(mode session)
    file(MAKE_DIRECTORY "${directory}/one" "${directory}/two")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/one/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/two/a.jpg")
    list(APPEND extra_args --recursive)
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 0 planned, 0 unchanged, 2 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'one/a.jpg': skipped: duplicate destination 'session-001/a.jpg'\nphotoc sort: 'two/a.jpg': skipped: duplicate destination 'session-001/a.jpg'\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "missing_date")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 1 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: missing or invalid EXIF capture date\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "invalid_jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(expected_exit 1)
    set(expected_stdout "Summary: 2 JPEG, 1 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'broken.jpg': skipped: invalid or truncated JPEG file\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "parent_file")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(WRITE "${directory}/2026" "keep this file\n")
    set(expected_exit 1)
    set(expected_stdout "Summary: 1 JPEG, 0 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: destination parent is not a directory\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "parent_symlink")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${root}/outside")
    file(CREATE_LINK "${root}/outside" "${directory}/2026" SYMBOLIC)
    set(expected_exit 1)
    set(expected_stdout "Summary: 1 JPEG, 0 planned, 0 unchanged, 1 blocked, 0 applied, 0 rolled back\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: destination parent is not a directory\nphotoc sort: preflight failed; no files changed\n")
    set(expect_unchanged TRUE)
elseif(CASE STREQUAL "directory_failure" OR CASE STREQUAL "runtime_rollback")
    execute_process(COMMAND id -u OUTPUT_VARIABLE user_id OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(user_id STREQUAL "0")
        message(STATUS "Skipping permission-based failure check as root")
        file(REMOVE_RECURSE "${root}")
        return()
    endif()
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    if(CASE STREQUAL "directory_failure")
        file(MAKE_DIRECTORY "${directory}/2026")
        file(CHMOD "${directory}/2026" PERMISSIONS OWNER_READ OWNER_EXECUTE)
        set(error_prefix "photoc sort: unable to create destination directory '2026/09/27': ")
        set(expected_stdout "Summary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 0 applied, 0 rolled back\n")
    else()
        file(MAKE_DIRECTORY "${directory}/2026/09/27")
        file(CHMOD "${directory}/2026/09/27" PERMISSIONS OWNER_READ OWNER_EXECUTE)
        set(error_prefix "photoc sort: apply failed for 'z.jpg' -> '2026/09/27/z.jpg': ")
        set(expected_stdout "Summary: 2 JPEG, 2 planned, 0 unchanged, 0 blocked, 0 applied, 1 rolled back\n")
    endif()
    set(expected_exit 1)
    set(expect_unchanged TRUE)
else()
    message(FATAL_ERROR "Unknown sort apply case: ${CASE}")
endif()

file(GLOB_RECURSE before_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT before_paths)
set(before_hashes "")
set(mapping_hashes "")
foreach(path IN LISTS before_paths)
    if(NOT IS_DIRECTORY "${root}/${path}" AND NOT IS_SYMLINK "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND before_hashes "${path}:${hash}")
    endif()
endforeach()
foreach(mapping IN LISTS mappings)
    string(REPLACE "|" ";" parts "${mapping}")
    list(GET parts 0 old_path)
    list(GET parts 1 new_path)
    file(SHA256 "${root}/${old_path}" hash)
    list(APPEND mapping_hashes "${new_path}:${hash}")
endforeach()

execute_process(
    COMMAND "${PHOTOC}" sort "${directory}" --by "${mode}" ${extra_args} --apply
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE actual_stdout
    ERROR_VARIABLE actual_stderr
)

file(GLOB_RECURSE after_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT after_paths)
set(after_hashes "")
foreach(path IN LISTS after_paths)
    if(NOT IS_DIRECTORY "${root}/${path}" AND NOT IS_SYMLINK "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND after_hashes "${path}:${hash}")
    endif()
endforeach()

if(CASE STREQUAL "directory_failure")
    file(CHMOD "${directory}/2026" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
elseif(CASE STREQUAL "runtime_rollback")
    file(CHMOD "${directory}/2026/09/27" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
endif()

if(NOT "${actual_exit}" STREQUAL "${expected_exit}" OR
   NOT actual_stdout STREQUAL expected_stdout)
    message(FATAL_ERROR "Unexpected result\nexpected exit: ${expected_exit}\nactual exit: ${actual_exit}\nexpected stdout: ${expected_stdout}\nactual stdout: ${actual_stdout}\nstderr: ${actual_stderr}")
endif()
if(NOT error_prefix STREQUAL "")
    string(FIND "${actual_stderr}" "${error_prefix}" position)
    if(NOT position EQUAL 0 OR actual_stderr STREQUAL "${error_prefix}\n")
        message(FATAL_ERROR "Unexpected failure diagnostic: ${actual_stderr}")
    endif()
elseif(NOT actual_stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${actual_stderr}")
endif()

if(expect_unchanged)
    if(NOT before_paths STREQUAL after_paths OR NOT before_hashes STREQUAL after_hashes)
        message(FATAL_ERROR "Failure or no-op changed the file inventory\nbefore: ${before_paths}\nafter: ${after_paths}")
    endif()
else()
    if(NOT after_paths STREQUAL expected_paths)
        message(FATAL_ERROR "Unexpected paths after apply\nexpected: ${expected_paths}\nactual: ${after_paths}")
    endif()
    foreach(mapping IN LISTS mappings)
        string(REPLACE "|" ";" parts "${mapping}")
        list(GET parts 0 old_path)
        list(GET parts 1 new_path)
        if(EXISTS "${root}/${old_path}")
            message(FATAL_ERROR "Old source remains: ${old_path}")
        endif()
        file(SHA256 "${root}/${new_path}" hash)
        list(FIND mapping_hashes "${new_path}:${hash}" position)
        if(position EQUAL -1)
            message(FATAL_ERROR "Moved file contents changed: ${new_path}")
        endif()
    endforeach()
endif()
file(REMOVE_RECURSE "${root}")
