if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-sort-session-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
file(MAKE_DIRECTORY "${directory}")
set(invocation "${PHOTOC}" sort "${directory}" --by session)
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(jpeg_count 0)
set(planned 0)
set(unchanged 0)
set(skipped 0)
set(has_summary TRUE)

if(CASE STREQUAL "default" OR CASE STREQUAL "gap_30m" OR
   CASE STREQUAL "gap_2h")
    # Source-path order differs from capture-time order.
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/a.JPEG")
    file(COPY_FILE "${FIXTURE_DIR}/session_1200.jpg" "${directory}/b.jpg")
    file(WRITE "${directory}/notes.txt" "ignore\n")
    set(jpeg_count 3)
    set(planned 3)
    if(CASE STREQUAL "gap_2h")
        list(APPEND invocation --gap 2h)
        set(expected_stdout "a.JPEG -> session-001/a.JPEG\nb.jpg -> session-001/b.jpg\nz.jpg -> session-001/z.jpg\n")
    else()
        if(CASE STREQUAL "gap_30m")
            list(APPEND invocation --gap 30m)
        endif()
        set(expected_stdout "a.JPEG -> session-001/a.JPEG\nb.jpg -> session-002/b.jpg\nz.jpg -> session-001/z.jpg\n")
    endif()
elseif(CASE STREQUAL "recursive")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    file(MAKE_DIRECTORY "${directory}/nested/deep")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/nested/a.jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1200.jpg" "${directory}/nested/deep/b.JPG")
    list(APPEND invocation --recursive --gap 30m)
    set(jpeg_count 3)
    set(planned 3)
    set(expected_stdout "nested/a.jpeg -> session-001/a.jpeg\nnested/deep/b.JPG -> session-002/b.JPG\nz.jpg -> session-001/z.jpg\n")
elseif(CASE STREQUAL "missing_date")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    set(jpeg_count 2)
    set(planned 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stdout "z.jpg -> session-001/z.jpg\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: missing or invalid EXIF capture date\n")
elseif(CASE STREQUAL "collision")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/session-001")
    file(WRITE "${directory}/session-001/a.jpg" "existing file\n")
    set(jpeg_count 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'a.jpg': skipped: destination exists 'session-001/a.jpg'\n")
elseif(CASE STREQUAL "duplicate")
    file(MAKE_DIRECTORY "${directory}/one" "${directory}/two")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/one/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/two/a.jpg")
    list(APPEND invocation --recursive)
    set(jpeg_count 2)
    set(skipped 2)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'one/a.jpg': skipped: duplicate destination 'session-001/a.jpg'\nphotoc sort: 'two/a.jpg': skipped: duplicate destination 'session-001/a.jpg'\n")
elseif(CASE STREQUAL "parent_conflict")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/a.jpg")
    file(WRITE "${directory}/session-001" "existing file\n")
    set(jpeg_count 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'a.jpg': skipped: destination parent is not a directory\n")
elseif(CASE STREQUAL "unchanged")
    file(MAKE_DIRECTORY "${directory}/session-001")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/session-001/a.jpg")
    list(APPEND invocation --recursive)
    set(jpeg_count 1)
    set(unchanged 1)
    set(expected_stdout "session-001/a.jpg -> session-001/a.jpg (unchanged)\n")
elseif(CASE STREQUAL "invalid_jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/z.jpg")
    set(jpeg_count 2)
    set(planned 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stdout "z.jpg -> session-001/z.jpg\n")
    set(expected_stderr "photoc sort: 'broken.jpg': skipped: invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "gap_zero")
    file(COPY_FILE "${FIXTURE_DIR}/session_1000.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/session_1030.jpg" "${directory}/b.jpg")
    list(APPEND invocation --gap 0m)
    set(jpeg_count 2)
    set(planned 2)
    set(expected_stdout "a.jpg -> session-001/a.jpg\nb.jpg -> session-002/b.jpg\n")
elseif(CASE STREQUAL "gap_with_date")
    set(invocation "${PHOTOC}" sort "${directory}" --by date --gap 30m)
    set(expected_exit 2)
    set(expected_stderr "photoc sort: --gap is only valid with --by session\n")
    set(has_summary FALSE)
elseif(CASE STREQUAL "gap_missing")
    list(APPEND invocation --gap)
    set(expected_exit 2)
    set(expected_stderr "photoc sort: option '--gap' requires a value\n")
    set(has_summary FALSE)
elseif(CASE STREQUAL "gap_duplicate")
    list(APPEND invocation --gap 30m --gap 2h)
    set(expected_exit 2)
    set(expected_stderr "photoc sort: option '--gap' may be specified only once\n")
    set(has_summary FALSE)
elseif(CASE MATCHES "^invalid_gap_")
    if(CASE STREQUAL "invalid_gap_no_unit")
        set(value "30")
    elseif(CASE STREQUAL "invalid_gap_uppercase")
        set(value "30M")
    elseif(CASE STREQUAL "invalid_gap_decimal")
        set(value "1.5h")
    elseif(CASE STREQUAL "invalid_gap_overflow")
        set(value "99999999999999999999h")
    else()
        message(FATAL_ERROR "Unknown gap case: ${CASE}")
    endif()
    list(APPEND invocation --gap "${value}")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: invalid gap '${value}'; use minutes or hours such as 30m or 2h\n")
    set(has_summary FALSE)
elseif(NOT CASE STREQUAL "empty")
    message(FATAL_ERROR "Unknown session case: ${CASE}")
endif()

if(has_summary)
    string(APPEND expected_stdout
           "Summary: ${jpeg_count} JPEG, ${planned} planned, ${unchanged} unchanged, ${skipped} blocked, 0 applied, 0 rolled back\n")
endif()

# Check names, directories, and bytes before and after every invocation.
file(GLOB_RECURSE before_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT before_paths)
set(before_hashes "")
foreach(path IN LISTS before_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND before_hashes "${path}:${hash}")
    endif()
endforeach()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE actual_stdout
    ERROR_VARIABLE actual_stderr
)

file(GLOB_RECURSE after_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT after_paths)
set(after_hashes "")
foreach(path IN LISTS after_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND after_hashes "${path}:${hash}")
    endif()
endforeach()
file(REMOVE_RECURSE "${root}")

if(NOT before_paths STREQUAL after_paths OR NOT before_hashes STREQUAL after_hashes)
    message(FATAL_ERROR "Session preview changed files or directories")
endif()
if(NOT "${actual_exit}" STREQUAL "${expected_exit}" OR
   NOT actual_stdout STREQUAL expected_stdout OR
   NOT actual_stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected result\nexpected exit: ${expected_exit}\nactual exit: ${actual_exit}\nexpected stdout: ${expected_stdout}\nactual stdout: ${actual_stdout}\nexpected stderr: ${expected_stderr}\nactual stderr: ${actual_stderr}")
endif()
