if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-rename-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
file(MAKE_DIRECTORY "${directory}")
set(format "{original}_{sequence}.{ext}")
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(summary_jpeg -1)
set(summary_planned 0)
set(summary_unchanged 0)
set(summary_blocked 0)

if(CASE STREQUAL "flat")
    set(summary_jpeg 2)
    set(summary_planned 2)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.JpEg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/inside.jpg")
    file(WRITE "${directory}/notes.txt" "ignore me\n")
    set(format "{date}_{camera}_{sequence}.{ext}")
    set(expected_stdout "a.JpEg -> 2024-01-02_Model A_0001.JpEg\nz.jpg -> 2026-09-27_Model Z_0002.jpg\n")
elseif(CASE STREQUAL "recursive" OR CASE STREQUAL "format_before_directory")
    set(summary_jpeg 3)
    set(summary_planned 3)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    file(MAKE_DIRECTORY "${directory}/nested/deep")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/b.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/deep/c.JPEG")
    set(expected_stdout "nested/b.jpg -> nested/b_0001.jpg\nnested/deep/c.JPEG -> nested/deep/c_0002.JPEG\nz.jpg -> z_0003.jpg\n")
elseif(CASE STREQUAL "missing_date")
    set(summary_jpeg 2)
    set(summary_planned 1)
    set(summary_blocked 1)
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(format "{date}_{sequence}.{ext}")
    set(expected_exit 1)
    set(expected_stdout "b.jpg -> 2026-09-27_0002.jpg\n")
    set(expected_stderr "photoc rename: 'a.jpg': skipped: metadata error: missing or invalid metadata for {date}\n")
elseif(CASE STREQUAL "missing_camera")
    set(summary_jpeg 1)
    set(summary_blocked 1)
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    set(format "{camera}_{sequence}.{ext}")
    set(expected_exit 1)
    set(expected_stderr "photoc rename: 'a.jpg': skipped: metadata error: missing or invalid metadata for {camera}\n")
elseif(CASE STREQUAL "collision")
    set(summary_jpeg 1)
    set(summary_blocked 1)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/taken.jpg")
    set(format "taken.jpg")
    set(expected_exit 1)
    set(expected_stderr "photoc rename: 'a.jpg': skipped: collision: destination exists 'taken.jpg'\n")
elseif(CASE STREQUAL "file_collision")
    set(summary_jpeg 1)
    set(summary_blocked 1)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(WRITE "${directory}/taken.txt" "keep this file\n")
    set(format "taken.txt")
    set(expected_exit 1)
    set(expected_stderr "photoc rename: 'a.jpg': skipped: collision: destination exists 'taken.txt'\n")
elseif(CASE STREQUAL "duplicate")
    set(summary_jpeg 2)
    set(summary_blocked 2)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(format "same.jpg")
    set(expected_exit 1)
    set(expected_stderr "photoc rename: 'a.jpg': skipped: collision: duplicate destination 'same.jpg'\nphotoc rename: 'b.jpg': skipped: collision: duplicate destination 'same.jpg'\n")
elseif(CASE STREQUAL "case_duplicate")
    set(summary_jpeg 2)
    set(summary_blocked 2)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.JPG")
    set(format "{date}.{ext}")
    set(expected_exit 1)
    set(expected_stderr "photoc rename: 'a.jpg': skipped: collision: duplicate destination '2026-09-27.jpg'\nphotoc rename: 'b.JPG': skipped: collision: duplicate destination '2026-09-27.JPG'\n")
elseif(CASE STREQUAL "separate_directories")
    set(summary_jpeg 2)
    set(summary_planned 2)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/b.jpg")
    set(format "same.jpg")
    set(expected_stdout "a.jpg -> same.jpg\nnested/b.jpg -> nested/same.jpg\n")
elseif(CASE STREQUAL "invalid_jpeg")
    set(summary_jpeg 2)
    set(summary_planned 1)
    set(summary_blocked 1)
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(expected_exit 1)
    set(expected_stdout "z.jpg -> z_0002.jpg\n")
    set(expected_stderr "photoc rename: 'broken.jpg': skipped: image decode error: invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "unchanged")
    set(summary_jpeg 1)
    set(summary_unchanged 1)
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    set(format "{original}.{ext}")
    set(expected_stdout "a.jpg -> a.jpg (unchanged)\n")
elseif(CASE STREQUAL "unknown_placeholder")
    set(format "{mystery}.{ext}")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: unknown placeholder {mystery}\n")
elseif(CASE STREQUAL "malformed_template")
    set(format "{date")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: invalid filename template at byte 0\n")
elseif(CASE STREQUAL "missing_format")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: expected one directory and --format <template>\nUsage: photoc rename <directory> --format <template> [--recursive] [--apply]\n")
elseif(CASE STREQUAL "missing_value")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: option '--format' requires a value\n")
elseif(CASE STREQUAL "duplicate_format")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: option '--format' may be specified only once\n")
elseif(CASE STREQUAL "missing_directory")
    set(expected_exit 1)
    set(directory "${root}/missing")
elseif(CASE STREQUAL "json")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: --json is not supported\n")
elseif(CASE STREQUAL "unknown_option")
    set(expected_exit 2)
    set(expected_stderr "photoc rename: unknown option '--bogus'\nTry 'photoc rename --help' for available options.\n")
elseif(CASE STREQUAL "empty")
    set(summary_jpeg 0)
elseif(NOT CASE STREQUAL "empty")
    message(FATAL_ERROR "Unknown rename case: ${CASE}")
endif()

if(NOT summary_jpeg EQUAL -1)
    string(APPEND expected_stdout
           "Summary: ${summary_jpeg} JPEG, ${summary_planned} planned, ${summary_unchanged} unchanged, ${summary_blocked} blocked, 0 applied, 0 rolled back\n")
endif()

# Keep a complete byte and path inventory to prove the preview changes nothing.
file(GLOB_RECURSE before_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT before_paths)
set(before_hashes "")
foreach(path IN LISTS before_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND before_hashes "${path}:${hash}")
    endif()
endforeach()

set(invocation "${PHOTOC}" rename "${directory}" --format "${format}")
if(CASE STREQUAL "recursive" OR CASE STREQUAL "separate_directories")
    list(APPEND invocation --recursive)
elseif(CASE STREQUAL "format_before_directory")
    set(invocation "${PHOTOC}" rename --format "${format}" "${directory}" --recursive)
elseif(CASE STREQUAL "missing_format")
    set(invocation "${PHOTOC}" rename "${directory}")
elseif(CASE STREQUAL "missing_value")
    set(invocation "${PHOTOC}" rename "${directory}" --format)
elseif(CASE STREQUAL "duplicate_format")
    list(APPEND invocation --format "${format}")
elseif(CASE STREQUAL "json")
    list(APPEND invocation --json)
elseif(CASE STREQUAL "unknown_option")
    list(APPEND invocation --bogus)
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE actual_stdout
    ERROR_VARIABLE actual_stderr
)

file(GLOB_RECURSE after_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT after_paths)
set(after_hashes "")
foreach(path IN LISTS after_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND after_hashes "${path}:${hash}")
    endif()
endforeach()
file(REMOVE_RECURSE "${root}")

if(NOT before_paths STREQUAL after_paths OR NOT before_hashes STREQUAL after_hashes)
    message(FATAL_ERROR "Rename preview changed files or directories")
endif()
if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${actual_stdout}\nstderr: ${actual_stderr}")
endif()
if(CASE STREQUAL "missing_directory")
    set(prefix "photoc rename: '${directory}': ")
    string(FIND "${actual_stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR actual_stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected missing-directory diagnostic: ${actual_stderr}")
    endif()
elseif(NOT actual_stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${actual_stderr}")
endif()
if(NOT actual_stdout STREQUAL expected_stdout)
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${actual_stdout}")
endif()
