if(NOT DEFINED PHOTOC OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/duplicates-${CASE}")
file(REMOVE_RECURSE "${root}")
file(MAKE_DIRECTORY "${root}")

function(expect_contains text expected)
    string(FIND "${text}" "${expected}" position)
    if(position EQUAL -1)
        message(FATAL_ERROR "Expected '${expected}' in:\n${text}")
    endif()
endfunction()

function(expect_absent text unexpected)
    string(FIND "${text}" "${unexpected}" position)
    if(NOT position EQUAL -1)
        message(FATAL_ERROR "Unexpected '${unexpected}' in:\n${text}")
    endif()
endfunction()

if(CASE STREQUAL "duplicates")
    file(WRITE "${root}/a.jpg" "abc")
    file(WRITE "${root}/b.png" "abc")
    file(WRITE "${root}/c.jpg" "abd")
    file(WRITE "${root}/unique.txt" "longer")
    file(CREATE_LINK "${root}/a.jpg" "${root}/alias.jpg" SYMBOLIC)
    set(arguments duplicates "${root}")
    set(expected_exit 0)
elseif(CASE STREQUAL "same_size_nonduplicates")
    file(WRITE "${root}/a.jpg" "abc")
    file(WRITE "${root}/b.jpg" "abd")
    set(arguments duplicates "${root}")
    set(expected_exit 0)
elseif(CASE STREQUAL "large_unique_same_size")
    # Same size, distinct 8 KiB prefixes: must not full-hash either file.
    string(REPEAT "A" 8192 prefix_a)
    string(REPEAT "B" 8192 prefix_b)
    file(WRITE "${root}/a.bin" "${prefix_a}")
    file(WRITE "${root}/b.bin" "${prefix_b}")
    set(arguments duplicates "${root}")
    set(expected_exit 0)
elseif(CASE STREQUAL "no_duplicates")
    file(WRITE "${root}/a.jpg" "a")
    file(WRITE "${root}/b.jpg" "bb")
    set(arguments duplicates "${root}")
    set(expected_exit 0)
elseif(CASE STREQUAL "multiple_groups")
    file(WRITE "${root}/a.jpg" "")
    file(WRITE "${root}/b.jpg" "")
    file(WRITE "${root}/c.jpg" "abc")
    file(WRITE "${root}/d.jpg" "abc")
    set(arguments duplicates "${root}")
    set(expected_exit 0)
elseif(CASE STREQUAL "nested")
    file(MAKE_DIRECTORY "${root}/nested")
    file(WRITE "${root}/a.jpg" "abc")
    file(WRITE "${root}/nested/b.jpg" "abc")
    execute_process(COMMAND "${PHOTOC}" duplicates "${root}"
                    RESULT_VARIABLE flat_exit OUTPUT_VARIABLE flat_stdout
                    ERROR_VARIABLE flat_stderr)
    if(NOT "${flat_exit}" STREQUAL "0" OR NOT flat_stderr STREQUAL "")
        message(FATAL_ERROR "Flat scan failed: ${flat_stderr}")
    endif()
    expect_contains("${flat_stdout}" "No duplicates found.")
    expect_contains("${flat_stdout}" "Files scanned: 1, hashed: 0, skipped: 0")
    set(arguments duplicates "${root}" --recursive)
    set(expected_exit 0)
elseif(CASE STREQUAL "missing")
    set(arguments duplicates "${root}/missing")
    set(expected_exit 1)
elseif(CASE STREQUAL "file")
    file(WRITE "${root}/a.jpg" "abc")
    set(arguments duplicates "${root}/a.jpg")
    set(expected_exit 1)
elseif(CASE STREQUAL "unreadable")
    file(WRITE "${root}/secret.jpg" "abc")
    file(WRITE "${root}/ok.jpg" "xyz")
    file(CHMOD "${root}/secret.jpg" PERMISSIONS OWNER_WRITE)
    execute_process(COMMAND test -r "${root}/secret.jpg" RESULT_VARIABLE readable)
    if(readable EQUAL 0)
        file(REMOVE_RECURSE "${root}")
        return()
    endif()
    set(arguments duplicates "${root}")
    set(expected_exit 1)
elseif(CASE STREQUAL "no_argument")
    set(arguments duplicates)
    set(expected_exit 2)
elseif(CASE STREQUAL "extra_argument")
    set(arguments duplicates "${root}" "${root}")
    set(expected_exit 2)
elseif(CASE STREQUAL "unknown_option")
    set(arguments duplicates "${root}" --bogus)
    set(expected_exit 2)
else()
    message(FATAL_ERROR "Unknown duplicate test case: ${CASE}")
endif()

execute_process(COMMAND "${PHOTOC}" ${arguments}
                RESULT_VARIABLE actual_exit OUTPUT_VARIABLE stdout
                ERROR_VARIABLE stderr)
if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()

if(expected_exit EQUAL 0)
    if(NOT stderr STREQUAL "")
        message(FATAL_ERROR "Unexpected stderr: ${stderr}")
    endif()
    expect_contains("${stdout}" "Exact duplicate files")
    if(CASE STREQUAL "duplicates")
        expect_contains("${stdout}" "Group 1 (3 B each, 2 files)")
        expect_contains("${stdout}" "  ${root}/a.jpg\n  ${root}/b.png")
        expect_absent("${stdout}" "  ${root}/c.jpg\n")
        expect_contains("${stdout}" "Total duplicate groups: 1")
        expect_contains("${stdout}" "Total duplicate files: 2")
        expect_contains("${stdout}" "Potential storage savings: 3 B")
        # Unique same-size "abd" is excluded by the prefix filter (hashed: 2).
        expect_contains("${stdout}" "Files scanned: 4, hashed: 2, skipped: 0")
        file(READ "${root}/a.jpg" first)
        file(READ "${root}/b.png" second)
        if(NOT first STREQUAL "abc" OR NOT second STREQUAL "abc")
            message(FATAL_ERROR "Duplicates command changed file contents")
        endif()
    elseif(CASE STREQUAL "nested")
        expect_contains("${stdout}" "  ${root}/a.jpg\n  ${root}/nested/b.jpg")
        expect_contains("${stdout}" "Total duplicate groups: 1")
        expect_contains("${stdout}" "Total duplicate files: 2")
        expect_contains("${stdout}" "Potential storage savings: 3 B")
        expect_contains("${stdout}" "Files scanned: 2, hashed: 2, skipped: 0")
    elseif(CASE STREQUAL "same_size_nonduplicates")
        expect_contains("${stdout}" "No duplicates found.")
        expect_contains("${stdout}" "Total duplicate groups: 0")
        expect_contains("${stdout}" "Total duplicate files: 0")
        expect_contains("${stdout}" "Files scanned: 2, hashed: 0, skipped: 0")
    elseif(CASE STREQUAL "large_unique_same_size")
        expect_contains("${stdout}" "No duplicates found.")
        expect_contains("${stdout}" "Total duplicate groups: 0")
        expect_contains("${stdout}" "Total duplicate files: 0")
        expect_contains("${stdout}" "Files scanned: 2, hashed: 0, skipped: 0")
    elseif(CASE STREQUAL "multiple_groups")
        expect_contains("${stdout}" "Group 1 (0 B each, 2 files)")
        expect_contains("${stdout}" "Group 2 (3 B each, 2 files)")
        expect_contains("${stdout}" "Total duplicate groups: 2")
        expect_contains("${stdout}" "Total duplicate files: 4")
        expect_contains("${stdout}" "Potential storage savings: 3 B")
        expect_contains("${stdout}" "Files scanned: 4, hashed: 4, skipped: 0")
    else()
        expect_contains("${stdout}" "No duplicates found.")
        expect_contains("${stdout}" "Files scanned: 2, hashed: 0, skipped: 0")
    endif()
else()
    if(CASE STREQUAL "unreadable")
        expect_contains("${stdout}" "Exact duplicate files")
        # Prefix filter skips full hashing when the only readable same-size file
        # has a unique prefix after the unreadable peer is dropped.
        expect_contains("${stdout}" "Files scanned: 2, hashed: 0, skipped: 1")
        expect_contains("${stderr}" "photoc duplicates: warning: '${root}/secret.jpg': file I/O error: unable to read file:")
        expect_absent("${stdout}" "${root}/secret.jpg")
    elseif(NOT stdout STREQUAL "")
        message(FATAL_ERROR "Expected no stdout, got: ${stdout}")
    endif()
    if(CASE STREQUAL "missing")
        expect_contains("${stderr}" "photoc duplicates: '${root}/missing':")
    elseif(CASE STREQUAL "file")
        expect_contains("${stderr}" "photoc duplicates: '${root}/a.jpg': file I/O error: unable to read directory:")
    elseif(CASE STREQUAL "no_argument" OR CASE STREQUAL "extra_argument")
        expect_contains("${stderr}" "expected exactly one directory")
    elseif(CASE STREQUAL "unknown_option")
        expect_contains("${stderr}" "unknown option '--bogus'")
    endif()
endif()

file(REMOVE_RECURSE "${root}")
