if(NOT DEFINED PHOTOC OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC and CASE are required")
endif()

set(invocation "${PHOTOC}")
if(CASE STREQUAL "help")
    list(APPEND invocation --help)
    set(expected_exit 0)
elseif(CASE STREQUAL "version")
    list(APPEND invocation --version)
    set(expected_exit 0)
elseif(CASE STREQUAL "no_args")
    set(expected_exit 2)
elseif(CASE STREQUAL "unknown")
    list(APPEND invocation unknown)
    set(expected_exit 2)
elseif(CASE STREQUAL "stub" AND DEFINED ARG)
    list(APPEND invocation "${ARG}")
    set(expected_exit 3)
else()
    message(FATAL_ERROR "Unknown test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()

if(CASE STREQUAL "help")
    if(NOT stdout MATCHES "Usage: photoc <command> \\[args\\]")
        message(FATAL_ERROR "Help is missing usage text: ${stdout}")
    endif()
    foreach(command IN ITEMS compress exif duplicates stats rename sort focus scrub)
        string(FIND "${stdout}" "  ${command}\n" command_position)
        if(command_position EQUAL -1)
            message(FATAL_ERROR "Help is missing ${command}: ${stdout}")
        endif()
    endforeach()
    if(NOT stderr STREQUAL "")
        message(FATAL_ERROR "Help wrote to stderr: ${stderr}")
    endif()
elseif(CASE STREQUAL "version")
    if(NOT stdout STREQUAL "photoc ${EXPECT_VERSION}\n" OR NOT stderr STREQUAL "")
        message(FATAL_ERROR "Unexpected version output\nstdout: ${stdout}\nstderr: ${stderr}")
    endif()
elseif(CASE STREQUAL "stub")
    if(NOT stdout STREQUAL "" OR NOT stderr STREQUAL "photoc: ${ARG} is not implemented yet\n")
        message(FATAL_ERROR "Unexpected stub output\nstdout: ${stdout}\nstderr: ${stderr}")
    endif()
elseif(CASE STREQUAL "no_args")
    if(NOT stdout STREQUAL "" OR NOT stderr MATCHES "Usage: photoc <command>")
        message(FATAL_ERROR "Unexpected no-argument output\nstdout: ${stdout}\nstderr: ${stderr}")
    endif()
elseif(CASE STREQUAL "unknown")
    if(NOT stdout STREQUAL "" OR NOT stderr MATCHES "unknown command 'unknown'")
        message(FATAL_ERROR "Unexpected unknown-command output\nstdout: ${stdout}\nstderr: ${stderr}")
    endif()
endif()
