if(NOT DEFINED PHOTOC OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-duplicates-json-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
if(CASE STREQUAL "escaped_paths")
    set(directory "${root}/photos-\"quoted\"-\nline-é")
endif()
file(MAKE_DIRECTORY "${directory}")

set(first "a.jpg")
set(second "b.png")
if(CASE STREQUAL "empty")
    # An empty scan still produces a complete JSON object.
elseif(CASE STREQUAL "no_duplicates")
    file(WRITE "${directory}/${first}" "abc")
    file(WRITE "${directory}/${second}" "abd")
elseif(CASE STREQUAL "multiple_groups")
    file(WRITE "${directory}/empty-a" "")
    file(WRITE "${directory}/empty-b" "")
    file(WRITE "${directory}/${first}" "abc")
    file(WRITE "${directory}/${second}" "abc")
elseif(CASE STREQUAL "recursive")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(WRITE "${directory}/${first}" "abc")
    file(WRITE "${directory}/nested/${second}" "abc")
    set(second "nested/${second}")
elseif(CASE STREQUAL "escaped_paths")
    set(first "a-\"quoted\"-back\\slash-\nline.jpg")
    file(WRITE "${directory}/${first}" "abc")
    file(WRITE "${directory}/${second}" "abc")
elseif(CASE STREQUAL "duplicates" OR CASE STREQUAL "before_command")
    file(WRITE "${directory}/${first}" "abc")
    file(WRITE "${directory}/${second}" "abc")
    file(WRITE "${directory}/different.jpg" "abd")
elseif(CASE STREQUAL "missing")
    set(directory "${root}/missing")
else()
    message(FATAL_ERROR "Unknown JSON case: ${CASE}")
endif()

if(CASE STREQUAL "before_command")
    set(invocation "${PHOTOC}" --json duplicates "${directory}")
else()
    set(invocation "${PHOTOC}" duplicates "${directory}" --json)
endif()
if(CASE STREQUAL "recursive")
    list(APPEND invocation --recursive)
endif()
execute_process(COMMAND ${invocation}
                RESULT_VARIABLE actual_exit OUTPUT_VARIABLE output
                ERROR_VARIABLE error_output)

if(CASE STREQUAL "missing")
    if(NOT actual_exit STREQUAL "1" OR NOT output STREQUAL "")
        message(FATAL_ERROR "Unexpected missing-directory result: ${actual_exit}\n${output}\n${error_output}")
    endif()
    string(FIND "${error_output}" "photoc duplicates: '${directory}': " position)
    if(NOT position EQUAL 0)
        message(FATAL_ERROR "Unexpected error: ${error_output}")
    endif()
    file(REMOVE_RECURSE "${root}")
    return()
endif()

if(NOT actual_exit STREQUAL "0" OR NOT error_output STREQUAL "")
    message(FATAL_ERROR "JSON command failed: ${actual_exit}\n${error_output}")
endif()

function(check_type expected)
    string(JSON actual ERROR_VARIABLE json_error TYPE "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected ${expected} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

function(check_value expected)
    string(JSON actual ERROR_VARIABLE json_error GET "${output}" ${ARGN})
    if(json_error OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "Expected '${expected}' at ${ARGN}; got '${actual}': ${json_error}")
    endif()
endfunction()

function(check_length expected)
    string(JSON actual ERROR_VARIABLE json_error LENGTH "${output}" ${ARGN})
    if(json_error OR NOT actual EQUAL expected)
        message(FATAL_ERROR "Expected length ${expected} at ${ARGN}; got ${actual}: ${json_error}")
    endif()
endfunction()

function(check_group index size digest first_path second_path)
    check_type(OBJECT groups ${index})
    check_type(NUMBER groups ${index} file_size_bytes)
    check_value("${size}" groups ${index} file_size_bytes)
    check_type(STRING groups ${index} sha256)
    check_value("${digest}" groups ${index} sha256)
    check_type(ARRAY groups ${index} paths)
    check_length(2 groups ${index} paths)
    check_type(STRING groups ${index} paths 0)
    check_type(STRING groups ${index} paths 1)
    check_value("${first_path}" groups ${index} paths 0)
    check_value("${second_path}" groups ${index} paths 1)
endfunction()

set(abc_hash "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad")
set(empty_hash "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855")

check_type(OBJECT)
check_type(STRING directory)
check_value("${directory}" directory)
check_type(BOOLEAN recursive)
if(CASE STREQUAL "recursive")
    check_value("ON" recursive)
else()
    check_value("OFF" recursive)
endif()
foreach(key IN ITEMS duplicate_group_count duplicate_file_count
                     potential_savings_bytes)
    check_type(NUMBER ${key})
endforeach()
check_type(ARRAY groups)

if(CASE STREQUAL "empty" OR CASE STREQUAL "no_duplicates")
    check_value("0" duplicate_group_count)
    check_value("0" duplicate_file_count)
    check_value("0" potential_savings_bytes)
    check_length(0 groups)
elseif(CASE STREQUAL "multiple_groups")
    check_value("2" duplicate_group_count)
    check_value("4" duplicate_file_count)
    check_value("3" potential_savings_bytes)
    check_length(2 groups)
    check_group(0 0 "${empty_hash}" "${directory}/empty-a" "${directory}/empty-b")
    check_group(1 3 "${abc_hash}" "${directory}/${first}" "${directory}/${second}")
else()
    check_value("1" duplicate_group_count)
    check_value("2" duplicate_file_count)
    check_value("3" potential_savings_bytes)
    check_length(1 groups)
    check_group(0 3 "${abc_hash}" "${directory}/${first}" "${directory}/${second}")
endif()

file(REMOVE_RECURSE "${root}")
