if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/format_size.cmake")

set(invocation "${PHOTOC}" exif)
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(check_io_error FALSE)

if(CASE STREQUAL "with_exif" OR CASE STREQUAL "with_gps" OR
   CASE STREQUAL "no_exif" OR CASE STREQUAL "large_size")
    if(CASE STREQUAL "with_exif")
        set(FILE_PATH "${FIXTURE_DIR}/with_exif.jpg")
    elseif(CASE STREQUAL "with_gps")
        set(FILE_PATH "${FIXTURE_DIR}/with_gps.jpeg")
    elseif(CASE STREQUAL "large_size")
        set(FILE_PATH "${CMAKE_CURRENT_BINARY_DIR}/exif-large-size.jpg")
        file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${FILE_PATH}")
        file(SIZE "${FILE_PATH}" initial_size)
        math(EXPR padding_size "2300000 - ${initial_size}")
        string(REPEAT "x" ${padding_size} padding)
        file(APPEND "${FILE_PATH}" "${padding}")
        unset(padding)
    else()
        set(FILE_PATH "${FIXTURE_DIR}/no_exif.jpg")
    endif()
    list(APPEND invocation "${FILE_PATH}")
    file(SIZE "${FILE_PATH}" FILE_SIZE)
    format_size("${FILE_SIZE}" FILE_SIZE)
    if(CASE STREQUAL "large_size")
        if(NOT FILE_SIZE STREQUAL "2.3 MB")
            message(FATAL_ERROR "Large EXIF fixture has wrong size: ${FILE_SIZE}")
        endif()
        set(snapshot_case with_exif)
    else()
        set(snapshot_case "${CASE}")
    endif()
    file(READ "${CMAKE_CURRENT_LIST_DIR}/fixtures/exif-${snapshot_case}.txt" snapshot)
    if(CASE STREQUAL "large_size")
        string(REPLACE "Name: with_exif.jpg" "Name: exif-large-size.jpg"
               snapshot "${snapshot}")
    endif()
    string(CONFIGURE "${snapshot}" expected_stdout @ONLY)
elseif(CASE STREQUAL "invalid")
    set(path "${FIXTURE_DIR}/invalid.jpg")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(expected_stderr "photoc exif: '${path}': image decode error: invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "unsupported")
    set(path "${FIXTURE_DIR}/unsupported.png")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(expected_stderr "photoc exif: '${path}': unsupported file: unsupported file type (expected .jpg, .jpeg, or Sony .arw)\n")
elseif(CASE STREQUAL "missing")
    set(path "${FIXTURE_DIR}/missing.jpg")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(check_io_error TRUE)
elseif(CASE STREQUAL "directory")
    set(path "${CMAKE_CURRENT_BINARY_DIR}/exif-directory.jpg")
    file(REMOVE_RECURSE "${path}")
    file(MAKE_DIRECTORY "${path}")
    list(APPEND invocation "${path}")
    set(expected_exit 1)
    set(check_io_error TRUE)
elseif(CASE STREQUAL "no_argument")
    set(expected_exit 2)
    set(expected_stderr "photoc exif: expected exactly one file\nUsage: photoc exif <file>\n")
elseif(CASE STREQUAL "extra_argument")
    list(APPEND invocation "${FIXTURE_DIR}/with_exif.jpg" "${FIXTURE_DIR}/no_exif.jpg")
    set(expected_exit 2)
    set(expected_stderr "photoc exif: expected exactly one file\nUsage: photoc exif <file>\n")
elseif(CASE STREQUAL "unknown_option")
    list(APPEND invocation --bogus "${FIXTURE_DIR}/with_exif.jpg")
    set(expected_exit 2)
    set(expected_stderr "photoc exif: unknown option '--bogus'\nTry 'photoc exif --help' for available options.\n")
else()
    message(FATAL_ERROR "Unknown EXIF test case: ${CASE}")
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE stdout
    ERROR_VARIABLE stderr
)
if(CASE STREQUAL "large_size")
    file(REMOVE "${FILE_PATH}")
endif()

if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${stdout}\nstderr: ${stderr}")
endif()
if(NOT stdout STREQUAL "${expected_stdout}")
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${stdout}")
endif()
if(check_io_error)
    set(prefix "photoc exif: '${path}': file I/O error: unable to read photo file: ")
    string(FIND "${stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected I/O error: ${stderr}")
    endif()
elseif(NOT stderr STREQUAL "${expected_stderr}")
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${stderr}")
endif()
