if(NOT DEFINED PHOTOC OR NOT DEFINED FIXTURE_DIR OR NOT DEFINED CASE)
    message(FATAL_ERROR "PHOTOC, FIXTURE_DIR, and CASE are required")
endif()

set(root "${CMAKE_CURRENT_BINARY_DIR}/photoc-sort-${CASE}")
file(REMOVE_RECURSE "${root}")
set(directory "${root}/photos")
file(MAKE_DIRECTORY "${directory}")
set(expected_exit 0)
set(expected_stdout "")
set(expected_stderr "")
set(jpeg_count 0)
set(planned 0)
set(unchanged 0)
set(skipped 0)

if(CASE STREQUAL "flat")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/a.JpEg")
    file(WRITE "${directory}/notes.txt" "ignore\n")
    file(MAKE_DIRECTORY "${directory}/nested")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/inside.jpg")
    set(jpeg_count 2)
    set(planned 2)
    set(expected_stdout "a.JpEg -> 2024/01/02/a.JpEg\nz.jpg -> 2026/09/27/z.jpg\n")
elseif(CASE STREQUAL "recursive")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    file(MAKE_DIRECTORY "${directory}/nested/deep")
    file(COPY_FILE "${FIXTURE_DIR}/with_alt_exif.jpg" "${directory}/nested/a.jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/nested/deep/c.JPG")
    set(jpeg_count 3)
    set(planned 3)
    set(expected_stdout "nested/a.jpeg -> 2024/01/02/a.jpeg\nnested/deep/c.JPG -> 2026/09/27/c.JPG\nz.jpg -> 2026/09/27/z.jpg\n")
elseif(CASE STREQUAL "missing_date")
    file(COPY_FILE "${FIXTURE_DIR}/no_exif.jpg" "${directory}/a.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/b.jpg")
    set(jpeg_count 2)
    set(planned 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stdout "b.jpg -> 2026/09/27/b.jpg\n")
    set(expected_stderr "photoc sort: 'a.jpg': skipped: metadata error: missing or invalid EXIF capture date\n")
elseif(CASE STREQUAL "collision")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(MAKE_DIRECTORY "${directory}/2026/09/27")
    file(WRITE "${directory}/2026/09/27/a.jpg" "existing file\n")
    set(jpeg_count 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'a.jpg': skipped: collision: destination exists '2026/09/27/a.jpg'\n")
elseif(CASE STREQUAL "duplicate" OR CASE STREQUAL "case_duplicate")
    file(MAKE_DIRECTORY "${directory}/one" "${directory}/two")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/one/a.jpg")
    if(CASE STREQUAL "duplicate")
        file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/two/a.jpg")
        set(other_name "a.jpg")
    else()
        file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/two/A.JPG")
        set(other_name "A.JPG")
    endif()
    set(jpeg_count 2)
    set(skipped 2)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'one/a.jpg': skipped: collision: duplicate destination '2026/09/27/a.jpg'\nphotoc sort: 'two/${other_name}': skipped: collision: duplicate destination '2026/09/27/${other_name}'\n")
elseif(CASE STREQUAL "parent_conflict")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/a.jpg")
    file(WRITE "${directory}/2026" "existing file\n")
    set(jpeg_count 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stderr "photoc sort: 'a.jpg': skipped: collision: destination parent is not a directory\n")
elseif(CASE STREQUAL "invalid_jpeg")
    file(COPY_FILE "${FIXTURE_DIR}/invalid.jpg" "${directory}/broken.jpg")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/z.jpg")
    set(jpeg_count 2)
    set(planned 1)
    set(skipped 1)
    set(expected_exit 1)
    set(expected_stdout "z.jpg -> 2026/09/27/z.jpg\n")
    set(expected_stderr "photoc sort: 'broken.jpg': skipped: image decode error: invalid or truncated JPEG file\n")
elseif(CASE STREQUAL "unchanged")
    file(MAKE_DIRECTORY "${directory}/2026/09/27")
    file(COPY_FILE "${FIXTURE_DIR}/with_exif.jpg" "${directory}/2026/09/27/a.jpg")
    set(jpeg_count 1)
    set(unchanged 1)
    set(expected_stdout "2026/09/27/a.jpg -> 2026/09/27/a.jpg (unchanged)\n")
elseif(CASE STREQUAL "missing_directory")
    set(directory "${root}/missing")
    set(expected_exit 1)
elseif(CASE STREQUAL "missing_by")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: expected one directory and --by date|session\nUsage: photoc sort <directory> --by date|session [--gap <duration>] [--recursive] [--apply]\n")
elseif(CASE STREQUAL "missing_value")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: option '--by' requires a value\n")
elseif(CASE STREQUAL "duplicate_by")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: option '--by' may be specified only once\n")
elseif(CASE STREQUAL "unknown_by")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: unsupported sort key 'size'; use 'date' or 'session'\n")
elseif(CASE STREQUAL "json")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: --json is not supported\n")
elseif(CASE STREQUAL "unknown_option")
    set(expected_exit 2)
    set(expected_stderr "photoc sort: unknown option '--bogus'\nTry 'photoc sort --help' for available options.\n")
elseif(NOT CASE STREQUAL "empty")
    message(FATAL_ERROR "Unknown sort case: ${CASE}")
endif()

if(CASE STREQUAL "flat" OR CASE STREQUAL "recursive" OR
   CASE STREQUAL "missing_date" OR CASE STREQUAL "collision" OR
   CASE STREQUAL "duplicate" OR CASE STREQUAL "case_duplicate" OR
   CASE STREQUAL "parent_conflict" OR CASE STREQUAL "invalid_jpeg" OR
   CASE STREQUAL "unchanged" OR CASE STREQUAL "empty")
    string(APPEND expected_stdout
           "Summary: ${jpeg_count} JPEG, ${planned} planned, ${unchanged} unchanged, ${skipped} blocked, 0 applied, 0 rolled back\n")
endif()

file(GLOB_RECURSE before_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT before_paths)
set(before_hashes "")
foreach(path IN LISTS before_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND before_hashes "${path}:${hash}")
    endif()
endforeach()

set(invocation "${PHOTOC}" sort "${directory}" --by date)
if(CASE STREQUAL "recursive" OR CASE STREQUAL "duplicate" OR
   CASE STREQUAL "case_duplicate" OR CASE STREQUAL "unchanged")
    list(APPEND invocation --recursive)
elseif(CASE STREQUAL "missing_by")
    set(invocation "${PHOTOC}" sort "${directory}")
elseif(CASE STREQUAL "missing_value")
    set(invocation "${PHOTOC}" sort "${directory}" --by)
elseif(CASE STREQUAL "duplicate_by")
    list(APPEND invocation --by date)
elseif(CASE STREQUAL "unknown_by")
    set(invocation "${PHOTOC}" sort "${directory}" --by size)
elseif(CASE STREQUAL "json")
    list(APPEND invocation --json)
elseif(CASE STREQUAL "unknown_option")
    list(APPEND invocation --bogus)
endif()

execute_process(
    COMMAND ${invocation}
    RESULT_VARIABLE actual_exit
    OUTPUT_VARIABLE actual_stdout
    ERROR_VARIABLE actual_stderr
)

file(GLOB_RECURSE after_paths LIST_DIRECTORIES true RELATIVE "${root}" "${root}/*")
list(SORT after_paths)
set(after_hashes "")
foreach(path IN LISTS after_paths)
    if(NOT IS_DIRECTORY "${root}/${path}")
        file(SHA256 "${root}/${path}" hash)
        list(APPEND after_hashes "${path}:${hash}")
    endif()
endforeach()
file(REMOVE_RECURSE "${root}")

if(NOT before_paths STREQUAL after_paths OR NOT before_hashes STREQUAL after_hashes)
    message(FATAL_ERROR "Sort preview changed files or directories")
endif()
if(NOT "${actual_exit}" STREQUAL "${expected_exit}")
    message(FATAL_ERROR "Expected exit ${expected_exit}, got ${actual_exit}\nstdout: ${actual_stdout}\nstderr: ${actual_stderr}")
endif()
if(CASE STREQUAL "missing_directory")
    set(prefix "photoc sort: '${directory}': ")
    string(FIND "${actual_stderr}" "${prefix}" position)
    if(NOT position EQUAL 0 OR actual_stderr STREQUAL "${prefix}\n")
        message(FATAL_ERROR "Unexpected missing-directory diagnostic: ${actual_stderr}")
    endif()
elseif(NOT actual_stderr STREQUAL expected_stderr)
    message(FATAL_ERROR "Unexpected stderr\nexpected: ${expected_stderr}\nactual: ${actual_stderr}")
endif()
if(NOT actual_stdout STREQUAL expected_stdout)
    message(FATAL_ERROR "Unexpected stdout\nexpected: ${expected_stdout}\nactual: ${actual_stdout}")
endif()
