# Match the CLI's decimal display for exact integer totals and rational averages.
function(format_size_fraction numerator denominator result)
    set(unit B)
    set(divisor 1)
    foreach(next_unit IN ITEMS KB MB GB TB PB EB)
        math(EXPR threshold "${denominator} * ${divisor} * 1000")
        if(numerator LESS threshold)
            break()
        endif()
        math(EXPR divisor "${divisor} * 1000")
        set(unit "${next_unit}")
    endforeach()
    math(EXPR scaled_denominator "${denominator} * ${divisor}")
    if(unit STREQUAL B)
        math(EXPR rounded "(${numerator} + ${scaled_denominator} / 2) / ${scaled_denominator}")
        set(${result} "${rounded} B" PARENT_SCOPE)
    else()
        math(EXPR tenths "(${numerator} * 10 + ${scaled_denominator} / 2) / ${scaled_denominator}")
        if(tenths EQUAL 10000 AND NOT unit STREQUAL EB)
            # These fixture-based tests never reach this case; the C unit test
            # checks unit promotion at the rounding boundary.
            message(FATAL_ERROR "Unexpected size rounding boundary")
        endif()
        math(EXPR whole "${tenths} / 10")
        math(EXPR fraction "${tenths} % 10")
        set(${result} "${whole}.${fraction} ${unit}" PARENT_SCOPE)
    endif()
endfunction()

function(format_size bytes result)
    format_size_fraction("${bytes}" 1 formatted)
    set(${result} "${formatted}" PARENT_SCOPE)
endfunction()
