#!/usr/bin/env python3
"""Generate small synthetic JPEG marker fixtures using only the standard library.

The base JPEG and invented EXIF come from the existing checked-in fixtures.
ICC data is an invented RGB matrix/TRC profile, not a calibrated camera profile.
No photographs, private metadata, or third-party profiles are imported.
"""

import hashlib
from pathlib import Path
import struct

ROOT = Path(__file__).resolve().parents[1]
DESTINATION = ROOT / "tests/fixtures/jpeg_metadata"

# Synthetic 3x2 grayscale JPEG generated by cjpeg -quality 90 -optimize.
GRAY_BASE = bytes.fromhex(
    "ffd8ffe000104a46494600010100000100010000ffdb0043000302020302020303030304"
    "030304050805050404050a070706080c0a0c0c0b0a0b0b0d0e12100d0e110e0b0b101610"
    "1113141515150c0f171816141812141514ffc0000b080002000301011100ffc400140001"
    "00000000000000000000000000000009ffc4001e10000103040300000000000000000000"
    "000301020600040507112131ffda0008010100003f004175ce9e815a41f0c104223810b0"
    "088d18f136ed6b5395f1119d57ffd9"
)



def marker(kind, payload):
    if len(payload) > 65533:
        raise ValueError("JPEG marker payload exceeds 65533 bytes")
    return bytes((0xFF, kind)) + struct.pack(">H", len(payload) + 2) + payload


def oriented_exif():
    source = (ROOT / "tests/fixtures/jpeg/with_gps.jpeg").read_bytes()
    length = int.from_bytes(source[4:6], "big")
    payload = source[6:4 + length]
    assert payload.startswith(b"Exif\0\0II")
    tiff = bytearray(payload[6:])
    offset = struct.unpack_from("<I", tiff, 4)[0]
    count = struct.unpack_from("<H", tiff, offset)[0]
    entries = [bytes(tiff[offset + 2 + i * 12:offset + 14 + i * 12])
               for i in range(count)]
    # Add invented opaque MakerNote bytes without rebuilding existing values.
    pointer_index = next(i for i, entry in enumerate(entries)
                         if struct.unpack_from("<H", entry)[0] == 0x8769)
    old_exif = struct.unpack_from("<I", entries[pointer_index], 8)[0]
    exif_count = struct.unpack_from("<H", tiff, old_exif)[0]
    exif_entries = [bytes(tiff[old_exif + 2 + i * 12:old_exif + 14 + i * 12])
                    for i in range(exif_count)]
    maker_note = b"photoc synthetic MakerNote\0\xff\x00opaque offsets\x12\x34"
    maker_offset = len(tiff)
    tiff.extend(maker_note)
    new_exif = len(tiff)
    exif_entries.append(struct.pack("<HHII", 0x927C, 7, len(maker_note), maker_offset))
    exif_entries.sort(key=lambda entry: struct.unpack_from("<H", entry)[0])
    tiff.extend(struct.pack("<H", len(exif_entries)) + b"".join(exif_entries) + b"\0" * 4)
    entries[pointer_index] = entries[pointer_index][:8] + struct.pack("<I", new_exif)
    entries.append(struct.pack("<HHIHH", 0x0112, 3, 1, 6, 0))
    entries.sort(key=lambda entry: struct.unpack_from("<H", entry)[0])
    struct.pack_into("<I", tiff, 4, len(tiff))
    tiff.extend(struct.pack("<H", len(entries)) + b"".join(entries) + b"\0" * 4)
    return b"Exif\0\0" + tiff


def icc_profile(grayscale=False):
    def xyz(x, y, z):
        return b"XYZ \0\0\0\0" + struct.pack(">iii", *(round(v * 65536) for v in (x, y, z)))

    tags = [(b"wtpt", xyz(0.9642, 1.0, 0.8249)),
            (b"rXYZ", xyz(0.5, 0.25, 0.1)),
            (b"gXYZ", xyz(0.3, 0.65, 0.15)),
            (b"bXYZ", xyz(0.1642, 0.1, 0.5749))]
    if grayscale:
        tags = tags[:1]
    for name in ((b"kTRC",) if grayscale else (b"rTRC", b"gTRC", b"bTRC")):
        tags.append((name, b"curv\0\0\0\0" + struct.pack(">IH", 1, 256)))
    header = bytearray(128)
    header[8:12] = b"\x02\x10\0\0"
    header[12:24] = b"mntrGRAYXYZ " if grayscale else b"mntrRGB XYZ "
    header[24:36] = struct.pack(">6H", 2026, 1, 1, 0, 0, 0)
    header[36:40] = b"acsp"
    header[68:80] = struct.pack(">iii", 63190, 65536, 54061)
    directory = bytearray(struct.pack(">I", len(tags)))
    body = bytearray()
    for name, payload in tags:
        directory.extend(name + struct.pack(">II", 128 + 4 + 12 * len(tags) + len(body), len(payload)))
        body.extend(payload)
        body.extend(b"\0" * (-len(body) % 4))
    profile = header + directory + body
    struct.pack_into(">I", profile, 0, len(profile))
    return bytes(profile)


def icc_chunk(profile, sequence=1, count=1):
    return b"ICC_PROFILE\0" + bytes((sequence, count)) + profile


def fixtures():
    base = (ROOT / "tests/fixtures/jpeg/no_exif.jpg").read_bytes()
    exif = marker(0xE1, oriented_exif())
    profile = icc_profile()
    icc = marker(0xE2, icc_chunk(profile))
    packet = (b'<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF '
              b'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
              b'<rdf:Description xmlns:dc="http://purl.org/dc/elements/1.1/" '
              b'dc:format="image/jpeg"/></rdf:RDF></x:xmpmeta>')
    xmp = marker(0xE1, b"http://ns.adobe.com/xap/1.0/\0" + packet)
    chunks = [profile[:100], profile[100:220], profile[220:]]
    # Physical order differs from sequence order, and other markers are interleaved.
    multi = (marker(0xE2, icc_chunk(chunks[2], 3, 3)) + xmp +
             marker(0xE2, icc_chunk(chunks[0], 1, 3)) + exif +
             marker(0xE2, icc_chunk(chunks[1], 2, 3)))
    extended = packet.replace(b"image/jpeg", b"image/jpeg extended fixture")
    guid = hashlib.md5(extended).hexdigest().upper().encode("ascii")
    main = (b'<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF '
            b'xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
            b'<rdf:Description xmlns:xmpNote="http://ns.adobe.com/xmp/note/" '
            b'xmpNote:HasExtendedXMP="' + guid + b'"/></rdf:RDF></x:xmpmeta>')
    extended_markers = marker(0xE1, b"http://ns.adobe.com/xap/1.0/\0" + main)
    for offset, portion in ((100, extended[100:]), (0, extended[:100])):
        extended_markers += marker(0xE1, b"http://ns.adobe.com/xmp/extension/\0" +
                                   guid + struct.pack(">II", len(extended), offset) + portion)
    def inject(markers):
        return base[:2] + markers + base[2:]
    return {
        "exif_only.jpg": inject(exif),
        "icc_only.jpg": inject(icc),
        # 3x2 PGM samples [0,64,128,192,224,255], cjpeg -quality 90 -optimize.
        "gray_icc.jpg": GRAY_BASE[:2] + marker(0xE2, icc_chunk(icc_profile(grayscale=True))) + GRAY_BASE[2:],
        "xmp_only.jpg": inject(xmp),
        "all_metadata.jpg": inject(exif + icc + xmp),
        "icc_multi.jpg": inject(multi),
        "icc_bad_sequence.jpg": inject(marker(0xE2, icc_chunk(profile, 1, 2))),
        "no_metadata.jpg": base,
        "gray_no_metadata.jpg": GRAY_BASE,
        "xmp_extended.jpg": inject(exif + extended_markers + icc),
    }


if __name__ == "__main__":
    DESTINATION.mkdir(parents=True, exist_ok=True)
    for name, data in fixtures().items():
        (DESTINATION / name).write_bytes(data)
    print(f"wrote JPEG marker fixtures under {DESTINATION}")
